### ISSUE TITLE
Issue when running  pycistarget for custom species zebrafish

### ISSUE THREAD

**Issue by JoGraesslin** [aertslab/scenicplus#137]
Hello,
I am trying to set up scenic plus for zebrafish. I used the Ensembl genome annotation for alignment and followed the workflow until pycistarget:
```
from scenicplus.wrappers.run_pycistarget import run_pycistarget
run_pycistarget(
    region_sets = region_sets,
    species='custom',
    custom_annot=custom_annotation,
    save_path = os.path.join(work_dir, 'motifs'),
    ctx_db_path = rankings_db,
    dem_db_path = scores_db,
    path_to_motif_annotations = motif_annotation,
    run_without_promoters = True,
    n_cpu = 8,
    _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
    annotation_version="2020"
    )
```
 It runs without an Error message, but the output is missing annotation:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/85675086/229102561-d4e0c22d-6e1a-4522-a5d5-8bf8de7a136b.png">

I have created a .tbl file from JASPAR using orthology data bases:
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/85675086/229104131-738c9fae-d317-42c5-a725-508ec9aab03f.png">

And a custom_annotation file based on the .gtf file looking like this
<img width="349" alt="image" src="https://user-images.githubusercontent.com/85675086/229103297-8f5b2557-a8b5-4001-8a28-dfe092a15778.png">

Do you have an idea what went wrong? I have used the Ensembl annotation all the way, and also tried with UCSC chromosomes. However, in all species, my Direct_annot and Orthology_annot columns are NaN.

 Any help would be appreciated, since I don't know anymore what else to try. Thanks!

_Originally posted by @JoGraesslin in https://github.com/aertslab/scenicplus/issues/56#issuecomment-1491748738_

**Comment by JoGraesslin** [comment]
Must have been an Issue with my annotation or .feather.
I have created a .tbl that uses the SCENIC+ public motif collection and renamed the human gene names from the .tbl to zebrafish gene names (using ensmbl biomart, oma and alliance orthology databases) and now it works :)

**Comment by fengweimin-maker** [comment]
> Must have been an Issue with my annotation or .feather. I have created a .tbl that uses the SCENIC+ public motif collection and renamed the human gene names from the .tbl to zebrafish gene names (using ensmbl biomart, oma and alliance orthology databases) and now it works :)
Hi@JoGraesslin,

I have built .feather and .tbl for species of Axolotl, but it failed, can you give some example of making .feather and .tbl for other species. 
If you help me, I will be very grateful.

Best,
Weimin

**Comment by mtrebelo** [comment]
Hi @JoGraesslin! I am running scenic+ with zebrafish data as well. I have the rankings_db and scores_db but not the motif_annotation. Would you mind sharing it? I would highly appreciate the help! Best, Maria

**Comment by mtrebelo** [comment]
Hi @JoGraesslin,

I am also using a zebrafish dataset with SCENIC+. I am exactly at this point of the analysis - I have the feather files for rankings_db and scores_db; I have created a custom_annotation based on .gtf but I am having issues with the .tbl file. I have done as you mention but the file must have some issue because it has not been able to run. Would you be able to make the tbl file available? Thanks a lot in advance

**Comment by fengweimin-maker** [comment]
> > > Must have been an Issue with my annotation or .feather. I have created a .tbl that uses the SCENIC+ public motif collection and renamed the human gene names from the .tbl to zebrafish gene names (using ensmbl biomart, oma and alliance orthology databases) and now it works :)
> > > Hi@JoGraesslin,
> > 
> > 
> > I have built .feather and .tbl for species of Axolotl, but it failed, can you give some example of making .feather and .tbl for other species. If you help me, I will be very grateful.
> > Best, Weimin
> 
> Hi @fengweimin-maker I downloaded the motif collections from here https://resources.aertslab.org/cistarget/motif_collections/. Then I renamed all gene names in the human.tbl file from the /snapshots folder with zebrafish orthologous gene names. These I found in different databases, (ensembl, oma, alliance) which contain orthologous genes based on amino acid similarity between human and zebrafish proteins. I dont know where you can find comparable databases like this for the axolotl, you might have to do some research in your community.
> 
> For the .feather, you use the consensus_regions.fa and the motif db as input:
> 
> ```
> consensus="/scenicplus/scATAC/consensus_peak_calling/consensus_regions.fa"
> motifs_cb="/v10nr_clust_public/singletons/
> motifs_list="/snapshots/motifs.lst"
> out="outdir"
> ncpu="20"
> 
> create_cistarget_motif_databases.py \
>     -f $consensus \
>     -M $motifs_cb \
>     -m $motifs_list \
>     -o $out \
>     -t $ncpu \
>     -g '#?$'
> ```
> 
> Hope this helps! Best, Jo

Thank you very much!

Best wish,
Weimin

**Comment by mtrebelo** [comment]
Hi @JoGraesslin, 

Thanks a lot! I have created it without problems. 

However, when running pycistarget, I am getting this: 

```
2023-06-08 09:34:58,354 pycisTarget_wrapper INFO     Loading cisTarget database for topics_otsu
2023-06-08 09:34:58,355 cisTarget    INFO     Reading cisTarget database
```

and then this error:

`AttributeError: ('PyRanges object has no attribute', 'Overlap')`

Did this by any chance occur with you?

Best, 
Maria
