### ISSUE TITLE
A bug we meet in running scenic

### ISSUE THREAD

**Issue by HelloWorldLTY** [aertslab/scenicplus#139]
Hi all, there is a bug when I run the tutorial for scenic:

For this code:

from pycisTopic.pseudobulk_peak_calling import export_pseudobulk
bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
                 variable = 'celltype',                                                                     # variable by which to generate pseubulk profiles, in this case we want pseudobulks per celltype
                 sample_id_col = 'sample_id',
                 chromsizes = chromsizes,
                 bed_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  # specify where pseudobulk_bed_files should be stored
                 bigwig_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bw_files/'),# specify where pseudobulk_bw_files should be stored
                 path_to_fragments = fragments_dict,                                                        # location of fragment fiels
                 n_cpu = 8,                                                                                 # specify the number of cores to use, we use ray for multi processing
                 normalize_bigwig = True,
                 remove_duplicates = True,
                 _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
                 split_pattern = '-')

I meet this bug:

    114 else:
    115     log.info("Reading fragments from " + path_to_fragments[sample_id])
--> 116     fragments_df = read_fragments_from_file(path_to_fragments[sample_id], use_polars=use_polars).df
    117     # Convert to int32 for memory efficiency
    118     fragments_df.Start = np.int32(fragments_df.Start)

File /gpfs/ysm/project/zhao/tl688/conda_envs/scbenchmark/lib/python3.8/site-packages/pycisTopic/utils.py:395, in read_fragments_from_file(fragments_bed_filename, use_polars)
    391 import polars as pl
    393 # Read fragments BED file with polars.
    394 df = (
--> 395     pl.read_csv(
    396         fragments_bed_filename,
    397         has_header=False,
    398         skip_rows=skip_rows,
    399         sep="\t",
    400         use_pyarrow=True,
    401         new_columns=bed_column_names[:nbr_columns],
    402     )
    403     .with_columns(
    404         [
    405             pl.col("Chromosome").cast(pl.Utf8),
    406             pl.col("Start").cast(pl.Int32),
    407             pl.col("End").cast(pl.Int32),
    408             pl.col("Name").cast(pl.Utf8),
    409         ]
    410     )
    411     .to_pandas()
    412 )
    414 # Convert "Name" column to pd.Categorical as groupby operations will be done on it later.
    415 df["Name"] = df["Name"].astype("category")

TypeError: read_csv() got an unexpected keyword argument 'sep'

It seems that polar does not support sep as an argument, but separator may work. What version of polars do you used? Thanks a lot.

**Comment by etiennedanis** [comment]
I don't know which version of polars they recommend but changing 'sep' to 'separator' in the file: /gpfs/ysm/project/zhao/tl688/conda_envs/scbenchmark/lib/python3.8/site-packages/pycisTopic/utils.py (around line 395) works.

**Comment by SeppeDeWinter** [comment]
@etiennedanis 

Thank you for suggesting the solution.

**Comment by ghuls** [comment]
This is fixed upstream for a while in https://github.com/aertslab/pycisTopic/commit/45b7e6679ca4f35baca85c442b232559160c3890
