### ISSUE TITLE
No objects to concatenate error, run_scenicplus: "Formatting eGRNs"

### ISSUE THREAD

**Issue by SidG13** [aertslab/scenicplus#142]
### Discussed in https://github.com/aertslab/scenicplus/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **SidG13** March 16, 2023</sup>
Hi,

I'm running into an issue related to the "Formatting eGRNs" step of run_scenicplus. Everything has run fine up to this point. I've run a previous sample before without issues as well, so this is new to me. Note that I'm using a custom species/annotation, so some fields are 'None'.

I ran:

```python
from scenicplus.wrappers.run_scenicplus import run_scenicplus
try:
    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['GEX_cell_cluster'],
        species = None,
        assembly = None,
        tf_file = '/home/administrator/Desktop/ExtraDrive1/Sid/data_manipulation/utoronto_human_tfs_v_1.01.txt',
        save_path = os.path.join(work_dir, 'scenicplus'),
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = False,
        path_bedToBigBed = '/home/administrator/Desktop/ExtraDrive1/Sid/data_manipulation',
        n_cpu = 8,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill'))
except Exception as e:
    #in case of failure, still save the object
    dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=4)
    raise(e)
```
And the eventual error is:
```bash
2023-03-16 18:06:42,551 GSEA         INFO     Subsetting on adjusted pvalue: 1, minimal NES: 0 and minimal leading edge genes 10
2023-03-16 18:06:42,552 GSEA         INFO     Merging eRegulons
2023-03-16 18:06:42,553 GSEA         INFO     Storing eRegulons in .uns[eRegulons].
2023-03-16 18:06:42,569 SCENIC+_wrapper INFO     Formatting eGRNs
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [13], line 22
     19 except Exception as e:
     20     #in case of failure, still save the object
     21     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=4)
---> 22     raise(e)

Cell In [13], line 3
      1 from scenicplus.wrappers.run_scenicplus import run_scenicplus
      2 try:
----> 3     run_scenicplus(
      4         scplus_obj = scplus_obj,
      5         variable = ['GEX_cell_cluster'],
      6         species = None,
      7         assembly = None,
      8         tf_file = '/home/administrator/Desktop/ExtraDrive1/Sid/data_manipulation/utoronto_human_tfs_v_1.01.txt',
      9         save_path = os.path.join(work_dir, 'scenicplus'),
     10         upstream = [1000, 150000],
     11         downstream = [1000, 150000],
     12         calculate_TF_eGRN_correlation = True,
     13         calculate_DEGs_DARs = True,
     14         export_to_loom_file = True,
     15         export_to_UCSC_file = False,
     16         path_bedToBigBed = '/home/administrator/Desktop/ExtraDrive1/Sid/data_manipulation',
     17         n_cpu = 8,
     18         _temp_dir = os.path.join(tmp_dir, 'ray_spill'))
     19 except Exception as e:
     20     #in case of failure, still save the object
     21     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=4)

File ~/anaconda2/envs/py38/lib/python3.8/site-packages/scenicplus/wrappers/run_scenicplus.py:195, in run_scenicplus(scplus_obj, variable, species, assembly, tf_file, save_path, biomart_host, upstream, downstream, region_ranking, gene_ranking, simplified_eGRN, calculate_TF_eGRN_correlation, calculate_DEGs_DARs, export_to_loom_file, export_to_UCSC_file, tree_structure, path_bedToBigBed, n_cpu, _temp_dir, save_partial, **kwargs)
    193 if 'eRegulon_metadata' not in scplus_obj.uns.keys():
    194     log.info('Formatting eGRNs')
--> 195     format_egrns(scplus_obj,
    196                   eregulons_key = 'eRegulons',
    197                   TF2G_key = 'TF2G_adj',
    198                   key_added = 'eRegulon_metadata')
    201 if 'eRegulon_signatures' not in scplus_obj.uns.keys():
    202     log.info('Converting eGRNs to signatures')

File ~/anaconda2/envs/py38/lib/python3.8/site-packages/scenicplus/utils.py:764, in format_egrns(scplus_obj, eregulons_key, TF2G_key, key_added)
    761 tf2g_data = scplus_obj.uns[TF2G_key].copy()
    762 tf2g_data.columns = ['TF', 'Gene', 'TF2G_importance', 'TF2G_regulation',
    763                      'TF2G_rho', 'TF2G_importance_x_abs_rho', 'TF2G_importance_x_rho']
--> 764 egrn_metadata = pd.concat([pd.merge(r2g_data[x], tf2g_data[tf2g_data.TF == r2g_data[x].TF[0]], on=[
    765                           'TF', 'Gene']) for x in range(len(egrn_list))])
    766 scplus_obj.uns[key_added] = egrn_metadata

File ~/anaconda2/envs/py38/lib/python3.8/site-packages/pandas/util/_decorators.py:317, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    311 if len(args) > num_allow_args:
    312     warnings.warn(
    313         msg.format(arguments=arguments),
    314         FutureWarning,
    315         stacklevel=find_stack_level(inspect.currentframe()),
    316     )
--> 317 return func(*args, **kwargs)

File ~/anaconda2/envs/py38/lib/python3.8/site-packages/pandas/core/reshape/concat.py:369, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    147 @deprecate_nonkeyword_arguments(version=None, allowed_args=["objs"])
    148 def concat(
    149     objs: Iterable[NDFrame] | Mapping[HashableT, NDFrame],
   (...)
    158     copy: bool = True,
    159 ) -> DataFrame | Series:
    160     """
    161     Concatenate pandas objects along a particular axis.
    162 
   (...)
    367     1   3   4
    368     """
--> 369     op = _Concatenator(
    370         objs,
    371         axis=axis,
    372         ignore_index=ignore_index,
    373         join=join,
    374         keys=keys,
    375         levels=levels,
    376         names=names,
    377         verify_integrity=verify_integrity,
    378         copy=copy,
    379         sort=sort,
    380     )
    382     return op.get_result()

File ~/anaconda2/envs/py38/lib/python3.8/site-packages/pandas/core/reshape/concat.py:426, in _Concatenator.__init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    423     objs = list(objs)
    425 if len(objs) == 0:
--> 426     raise ValueError("No objects to concatenate")
    428 if keys is None:
    429     objs = list(com.not_none(*objs))

ValueError: No objects to concatenate
```
My scenicplus object looks fine, everything is populated except eRegulons. 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/36648847/225772936-c3395dd1-d04a-453f-82a0-e5ae0ed0ced3.png">

The two dataframes which I think are causing the issue look OK to me?
<img width="975" alt="image" src="https://user-images.githubusercontent.com/36648847/225775002-76954c9b-fa6c-4c35-b453-97babae89eb7.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/36648847/225775066-df88b897-44c3-41c4-ba20-4467973049f4.png">

As suggested in the discussion, I re-ran ```build_grn``` but still ran into the same problem eventually. No eRegulons were made. 

The only things I may have done differently were DAR prediction. DARs were kept only if the dataframe was not empty. I used this code from this [issue](https://github.com/aertslab/scenicplus/issues/87).
<img width="771" alt="image" src="https://user-images.githubusercontent.com/36648847/232136911-495e7fb5-8983-47f4-9bc0-ca59209cd6a8.png">

As you can see, only cell clusters 3, 5 and 11 had any DARs. Would this cause any of the downstream issues?
<img width="994" alt="image" src="https://user-images.githubusercontent.com/36648847/232137031-0ac38116-ea99-42a9-a025-5118276895be.png">

Does anyone have an idea what I could be missing? Thanks!
</div>

**Comment by SidG13** [comment]
Hi @SeppeDeWinter, sorry for the late reply. I was running a different sample and actually got the same error, so I'll show you the output of those objects. Again, the pipeline fails at the ```Formatting eGRNs``` step of the pipeline.

<img width="1103" alt="image" src="https://github.com/aertslab/scenicplus/assets/36648847/e09464ac-45e3-4b27-9f34-98e3b611ecdb">
<img width="1087" alt="image" src="https://github.com/aertslab/scenicplus/assets/36648847/dec6024a-cbd8-4d7d-862a-2632664b1024">

**Comment by Harrison-Q-Ma** [comment]
@SidG13 Hello there. Did you end up solving this issue? I am running into the same error and my ``scplus_obj.uns['eRegulons']`` is also empty. Please let me know if you were able to solve this. Thanks!

**Comment by SidG13** [comment]
Hi @Harrison-Q-Ma , no I haven't been able to solve it. I'll leave this open, it may be a bug but not sure.

**Comment by SeppeDeWinter** [comment]
Hi both.

Not sure what is going wrong here. 
I made a lot of updates in the mean time (development branch), maybe that code works better for you? 

See this discussion on how to use it: https://github.com/aertslab/scenicplus/discussions/202


Best,

Seppe

**Comment by SeppeDeWinter** [comment]
Hi @SidG13 

If you could sent me the yaml file that would help.

Also in case of custom annotation, just place the annotation file at the location specified by `genome_annotation` (same goes for the chromsizes).

Best,

Seppe

**Comment by SidG13** [comment]
Just an update from @SeppeDeWinter, it seems my gene expression half of the multiome assay didn't work very well (high sparsity), and this caused the error that I got. eRegulons weren't made because the TF-to-gene links were bad.

**Comment by teresho4** [comment]
I had the same issue, apparently in the dataset all regulons didn't pass 'min_target_genes' parameter. You can decrease this number. In general, it is sad, because my data looks good in terms of quality, regular multiome, just small n cells (~2000), not sure why it can't find at least something reasonable.
