### ISSUE TITLE
Issue with 10x multiome pbmc tutorial

### ISSUE THREAD

**Issue by etiennedanis** [aertslab/scenicplus#146]
Hello,
Thank you for creating Scenic+!
Following your 10x multiome pbmc tutorial, I get stuck at the QC part of the ATAC-seq analysis.
Instead of getting the following figures:
![image](https://user-images.githubusercontent.com/11301740/233700090-adf1704e-bcf1-4716-a12b-480e248bc243.png)

I get the following:
![image](https://user-images.githubusercontent.com/11301740/233700133-02d282bd-382b-4b51-9958-8ba24a6be2a1.png)

Instead of getting 2521 barcodes passing QC stats, I get 0.

All different steps of your tutorial seem to work well, except the compute_qc_stats.
Here is the code where I get an error message:

**
metadata_bc, profile_data_dict = compute_qc_stats(
                fragments_dict = fragments_dict,
                tss_annotation = annot,
                stats=['barcode_rank_plot', 'duplicate_rate', 'insert_size_distribution', 'profile_tss', 'frip'],
                label_list = None,
                path_to_regions = path_to_regions,
                n_cpu = 1,
                valid_bc = None,
                n_frag = 100,
                n_bc = None,
                tss_flank_window = 1000,
                tss_window = 50,
                tss_minimum_signal_window = 100,
                tss_rolling_window = 10,
                remove_duplicates = True,
                _temp_dir = os.path.join(tmp_dir + 'ray_spill'))
**
 

And here is the error message I get:
**
/home/etienne/Documents/pycisTopic/pycisTopic/qc.py:564: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  TSS_matrix[x] = 0
**

I also get the following error messages when using the function plot_barcode_metrics():
**
/home/etienne/Documents/tools/pycisTopic/pycisTopic/qc.py:1871: UserWarning: 
`distplot` is a deprecated function and will be removed in seaborn v0.14.0.
Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).
For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751
  sns.distplot(
/home/etienne/Documents/tools/pycisTopic/pycisTopic/qc.py:1886: UserWarning: 
`distplot` is a deprecated function and will be removed in seaborn v0.14.0.
Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).
For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751
  sns.distplot(
**
I changed distplot for histplot or displot and got rid of these messages but it did not change the figures or the number of barcodes passing QC.

Is there anything I can try to fix this issue?
Thank you very much in advance.
Etienne

**Comment by HelloWorldLTY** [comment]
Hi, I have the same question, and my filtered cells aer 0. No barcodes pass the QC.

**Comment by SITRR** [comment]
My apologies for re-opening the issue, @SeppeDeWinter, but I'm using pandas 1.5 and still encounter the same error as @HelloWorldLTY with the create_cistopic_object_from_fragments function. It's apparent that some of my samples don't pass the QC thresholds based on a FRIP cutoff of 0.4 (I've attached the QC plots). Could these samples be causing the problem? Thanks!

[combined_qc.pdf](https://github.com/aertslab/scenicplus/files/14528754/combined_qc.pdf)

**Comment by TingTingShao** [comment]
Hi, 

Pandas version is Version: 1.5.0, but I had the same issue, 0 barcodes passed QC stats. The following is the requirements version.  
[requirement.txt](https://github.com/aertslab/scenicplus/files/14549701/requirement.txt)


Looking forward to your reply.
TingTing

**Comment by TingTingShao** [comment]
To add to my previous question, I changed the python version back to Python 3.8.18

**Comment by TingTingShao** [comment]
> To add to my previous question, I changed the python version back to Python 3.8.18

after rerunning the QC step, the problem is solved!

**Comment by Stack7** [comment]
@TingTingShao did you reinstall scenicplus in a python env with the version: 3.8.18?

**Comment by Stack7** [comment]
Hello all!
@SeppeDeWinter  unluckily even the downgrade of the Pandas version does not solve the issue. I have got yhe same issue and I am working in a Fedora 40 HPC in a conda environment with Python version 3.11 as suggested in the tutorial
thanks for your help in advance!

**Comment by 1226235** [comment]
Hi all, 
Does anyone have a solution to work around this problem? I also encountered this problem, and unfortunately, the HPC I use no longer supports Python 3.8. Does anyone get scenicplus to work with Python >= 3.10? Thanks for any suggestions in advance.
