### ISSUE TITLE
Intersection of gene_names and tf_names is empty

### ISSUE THREAD

**Issue by Tomoya89** [aertslab/scenicplus#155]
Thank you for developing a great tool to analyze multiome data!

We have been analyzing our own scMultiome data of medaka fish using the 10x multiome tutorial as a guide, and we managed to get to the last step (run_scenicplus). However, we got the following error in the SCENIC+_wrapper INFO Inferring TF to gene relationships step (It seems "Calculating region to gene correlation, using SR method" step seems to have been completed without any problems).
ValueError: Intersection of gene_names and tf_names is empty.

The following is the command that was executed.
```
from scenicplus.wrappers.run_scenicplus import run_scenicplus
try:
    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['GEX_celltype'],
        species = 'custom',
        assembly = 'ol',
        tf_file = 'create_cisTarget_databases/motif_list_medaka.txt',
        save_path = os.path.join(work_dir),
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = True,
        path_bedToBigBed = 'scenicplus_medaka',
        n_cpu = 12,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill')
    )
except Exception as e:
    #in case of failure, still save the object
    dill.dump(scplus_obj, open(os.path.join(work_dir, 'scplus_obj.pkl'), 'wb'), protocol=-1)
    raise(e)
```

The results of the contents of scenicplus is as follow.
![スクリーンショット 2023-05-17 12 15 53](https://github.com/aertslab/scenicplus/assets/26383618/9e3fa94e-d637-4da3-a77d-12b251195f5d)

It would be grateful if you could help us to solve this problem.
Thank you.

**Comment by SidG13** [comment]
Not the developer, but could you double check the ```motif_list_medaka.txt``` file? It should be a list of TF (gene) names, I think maybe you may have used some sort of motif format based on the name of that file?

**Comment by Tomoya89** [comment]
Thank you very much. You are right, I checked the contents of the file and it is a list of motifs. I changed it to a list of transcription factors and it seemed to work fine.
