### ISSUE TITLE
How changing the cell annotation influences the SCENIC+ inference?

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [aertslab/scenicplus#160]
Please don't post an issue but post your issue in the discussions instead: https://github.com/aertslab/scenicplus/discussions

Thanks you :)

**Comment by SeppeDeWinter** [comment]
Hi,

For multiome data the cell annotation will not influence the eGRN inference.
For non-multiome it will, because it is used to pair scATAC and scRNA-seq cells.

Best,

Seppe
