### ISSUE TITLE
Low "importance" score using RF model comapred to GBM model

### ISSUE THREAD

**Issue by piyushjo15** [aertslab/scenicplus#171]
Hi,

Thanks for developing the wonderful SCENIC+ pipeline.

I am using SCENIC+ to perform eGRN analysis using multiomic data. I ran the pipeline in the default mode and was able to get all the outputs. 
In order to tweak some parameters, I decided to use RF model instead of GBM, as if I am not wrong, SCENIC, GENIE3 and GRNBOOST use RF model?

However, I am observing very low importance score for TF2G gene associations. 
I used 48 topics, for a dataset containing 7263 cells, 2646 HVG and 91967 regions. using GBM apporach the max importance score for TF2G is ~291 with mean being ~12. Using RF model,  I tried both sqrt and 0.3 max_features,  I get around 0.132 max and 0.014 mean. I just want to know why is RF model giving such low scores, which in normal SCENIC analysis doesn't happen.

Would be great to get your feedback on this issue~

Thanks!

**Comment by SeppeDeWinter** [comment]
Hi,

It's correct that SCENIC and GENIE3 use RF.
However, from pySCENIC on we started using GBM, which is much faster and (almost) as accurate as RF.

For SCENIC+ we use use the relative importance scores, so their absolute value does not really matter, as long as the order of the target genes is still correct.

Best,

Seppe
