### ISSUE TITLE
Installing SCENIC+ on M2 MACs - folow up on patch

### ISSUE THREAD

**Issue by GeneVector5** [aertslab/scenicplus#186]
@SeppeDeWinter I looked at your comment here: https://github.com/aertslab/scenicplus/issues/101#issuecomment-1425405135

However, I am still having SCENIC+ installation errors and wanted to ask if there any updates for installations on M2 apple chip computer.  

For your recommendation for Patch MACS2, I am getting an error in the terminal that I do not know how to fix. Do you have any recommendations?

```
(scenicplus_env) sara@saras-MacBook-Pro MACS-2.2.7.1 % sed -i 's/install_requires = \[f"numpy>={numpy_requires}",\]/install_requires = \[f"numpy{numpy_requires}",\]/' setup.py
sed: 1: "setup.py": unterminated substitute pattern

```
Any thoughts @wakelin-g @ghuls  @degrainger ? Based on the discussion it seems like you guys figured out how to install SCENIC+ on macs ?

**Comment by SeppeDeWinter** [comment]
Hi @GeneVector5 

MACS2 has been updated already so the patch is not necessary anymore.

```bash
pip install MACS2
```

Should just work.

Moreover, our software has not been developed/tested on MacOS.

I would suggest trying to run it on a linux system.


Best,

Seppe
