### ISSUE TITLE
Singularity cannot install scenicplus.sif, has the container file been deleted?

### ISSUE THREAD

**Issue by hgl2017** [aertslab/scenicplus#187]
```singularity build scenicplus.sif oci-archive://scenicplus_img.tar```

The result of running the script is as follows.

```INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error extracting the OCI archive file: open scenicplus_img.tar: no such file or directory```

Why is this so, can you help me answer it? Thanks！

**Comment by ghuls** [comment]
You have to create the tar file firs with podman or docker. See: https://github.com/aertslab/scenicplus#creating-a-dockersingularity-image

**Comment by hgl2017** [comment]
I see, thank you
