### ISSUE TITLE
Exception: The embedding should have two columns. in _export_minimal_loom

### ISSUE THREAD

**Issue by SeppeDeWinter** [aertslab/scenicplus#21]
When exporting a loom file from scenicplus the expection `Exception: The embedding should have two columns` is thrown.
This is caused by the PCA dimensionality reduction which has more than two columns, in this case we should take the first two. 

(will commit a fix soon, writing this issue so I don't forget).

**Comment by WangRong423** [comment]
Hi, Seppe
I encountered this Exception and found where you updated it. But I don't know how to update this into my version. Could you tell me more about it? Thank you very much!
my version is 0.1.dev455+g0173233
