### ISSUE TITLE
Using SCENIC+ in jupyter-notebook on a HPC

### ISSUE THREAD

**Issue by BartTheeuwes** [aertslab/scenicplus#24]
Hi, 

Congratulations with the development of Scenic+, it looks like a really useful tool and I can't wait to try it out. 

**Describe the bug**
I am trying to run the tutorial notebooks on a HPC cluster, but this is causing problems with the ray parallelization for me. My notebooks run through an interactive SLURM job. Do you have any explanation available on how to get Ray to work in this context? Many thanks in advance.

**To Reproduce**
_SLURM submission script:_

#!/bin/bash
#SBATCH -p cclake 
#SBATCH -A gottgens-sl2-cpu
#SBATCH -N 1
#SBATCH -n 12

### get/set tunneling info
XDG_RUNTIME_DIR=""
ipnport=$(shuf -i8000-9999 -n1)
ipnip=$(hostname -i)
### Start jupyter
jupyter-lab --no-browser --port=$ipnport --ip=$ipnip

_Then in Jupyter-notebook ( this or any other command that has the n_pcu option) :_

    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['GEX_celltype'],
        species = 'hsapiens',
        assembly = 'hg38',
        tf_file = 'pbmc_tutorial/data/utoronto_human_tfs_v_1.01.txt',
        save_path = os.path.join(work_dir, 'scenicplus'),
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = True,
        path_bedToBigBed = 'pbmc_tutorial',
        n_cpu = 5,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill'))

It seems to run with n_cpu=None, but this takes a really long time.

**Error output**
2022-08-22 09:17:00,608	INFO services.py:1470 -- View the Ray dashboard at http://127.0.0.1:8267/
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
File ~/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ray/node.py:303, in Node.__init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    302 try:
--> 303     ray._private.services.wait_for_node(
    304         self.redis_address,
    305         self.gcs_address,
    306         self._plasma_store_socket_name,
    307         self.redis_password,
    308     )
    309 except TimeoutError:

File ~/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ray/_private/services.py:397, in wait_for_node(redis_address, gcs_address, node_plasma_store_socket_name, redis_password, timeout)
    396         time.sleep(0.1)
--> 397 raise TimeoutError("Timed out while waiting for node to startup.")

TimeoutError: Timed out while waiting for node to startup.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Input In [18], in <cell line: 2>()
     20 except Exception as e:
     21     #in case of failure, still save the object
     22     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)
---> 23     raise(e)

Input In [18], in <cell line: 2>()
      1 from scenicplus.wrappers.run_scenicplus import run_scenicplus
      2 try:
----> 3     run_scenicplus(
      4         scplus_obj = scplus_obj,
      5         variable = ['GEX_celltype'],
      6         species = 'hsapiens',
      7         assembly = 'hg38',
      8         tf_file = 'pbmc_tutorial/data/utoronto_human_tfs_v_1.01.txt',
      9         save_path = os.path.join(work_dir, 'scenicplus'),
     10         biomart_host = biomart_host,
     11         upstream = [1000, 150000],
     12         downstream = [1000, 150000],
     13         calculate_TF_eGRN_correlation = True,
     14         calculate_DEGs_DARs = True,
     15         export_to_loom_file = True,
     16         export_to_UCSC_file = True,
     17         path_bedToBigBed = 'pbmc_tutorial',
     18         n_cpu = 5,
     19         _temp_dir = os.path.join(tmp_dir, 'ray_spill'))
     20 except Exception as e:
     21     #in case of failure, still save the object
     22     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)

File /rds/project/rds-SDzz0CATGms/users/bt392/software/github/scenicplus/src/scenicplus/wrappers/run_scenicplus.py:141, in run_scenicplus(scplus_obj, variable, species, assembly, tf_file, save_path, biomart_host, upstream, downstream, region_ranking, gene_ranking, simplified_eGRN, calculate_TF_eGRN_correlation, calculate_DEGs_DARs, export_to_loom_file, export_to_UCSC_file, tree_structure, path_bedToBigBed, n_cpu, _temp_dir)
    139 if 'region_to_gene' not in scplus_obj.uns.keys():
    140     log.info('Inferring region to gene relationships')
--> 141     calculate_regions_to_genes_relationships(scplus_obj, 
    142                     ray_n_cpu = n_cpu, 
    143                     _temp_dir = _temp_dir,
    144                     importance_scoring_method = 'GBM',
    145                     importance_scoring_kwargs = GBM_KWARGS)
    147 if 'TF2G_adj' not in scplus_obj.uns.keys():
    148     log.info('Inferring TF to gene relationships')

File /rds/project/rds-SDzz0CATGms/users/bt392/software/github/scenicplus/src/scenicplus/enhancer_to_gene.py:661, in calculate_regions_to_genes_relationships(SCENICPLUS_obj, search_space_key, mask_expr_dropout, genes, importance_scoring_method, importance_scoring_kwargs, correlation_scoring_method, ray_n_cpu, add_distance, key_added, inplace, **kwargs)
    658 log.info(
    659     f'Calculating region to gene importances, using {importance_scoring_method} method')
    660 start_time = time.time()
--> 661 region_to_gene_importances = _score_regions_to_genes(SCENICPLUS_obj,
    662                                                     search_space=search_space,
    663                                                     mask_expr_dropout=mask_expr_dropout,
    664                                                     genes=genes,
    665                                                     regressor_type=importance_scoring_method,
    666                                                     regressor_kwargs=importance_scoring_kwargs,
    667                                                     ray_n_cpu=ray_n_cpu,
    668                                                     **kwargs)
    669 log.info('Took {} seconds'.format(time.time() - start_time))
    671 # calculate region to gene correlation

File /rds/project/rds-SDzz0CATGms/users/bt392/software/github/scenicplus/src/scenicplus/enhancer_to_gene.py:534, in _score_regions_to_genes(SCENICPLUS_obj, search_space, mask_expr_dropout, genes, regressor_type, ray_n_cpu, regressor_kwargs, **kwargs)
    532 ACC_df = SCENICPLUS_obj.to_df(layer='ACC')
    533 if ray_n_cpu != None:
--> 534     ray.init(num_cpus=ray_n_cpu, **kwargs)
    535     try:
    536         jobs = []

File ~/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ray/worker.py:1039, in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, namespace, runtime_env, storage, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _temp_dir, _metrics_export_port, _system_config, _tracing_startup_hook, _node_name, **kwargs)
    997     ray_params = ray._private.parameter.RayParams(
    998         node_ip_address=node_ip_address,
    999         raylet_ip_address=raylet_ip_address,
   (...)
   1033         node_name=_node_name,
   1034     )
   1035     # Start the Ray processes. We set shutdown_at_exit=False because we
   1036     # shutdown the node in the ray.shutdown call that happens in the atexit
   1037     # handler. We still spawn a reaper process in case the atexit handler
   1038     # isn't called.
-> 1039     _global_node = ray.node.Node(
   1040         head=True, shutdown_at_exit=False, spawn_reaper=True, ray_params=ray_params
   1041     )
   1042 else:
   1043     # In this case, we are connecting to an existing cluster.
   1044     if num_cpus is not None or num_gpus is not None:

File ~/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ray/node.py:310, in Node.__init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    303     ray._private.services.wait_for_node(
    304         self.redis_address,
    305         self.gcs_address,
    306         self._plasma_store_socket_name,
    307         self.redis_password,
    308     )
    309 except TimeoutError:
--> 310     raise Exception(
    311         "The current node has not been updated within 30 "
    312         "seconds, this could happen because of some of "
    313         "the Ray processes failed to startup."
    314     )
    315 node_info = ray._private.services.get_node_to_connect_for_driver(
    316     self.redis_address,
    317     self.gcs_address,
    318     self._raylet_ip_address,
    319     redis_password=self.redis_password,
    320 )
    321 self._ray_params.node_manager_port = node_info.node_manager_port

Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup.

**Version (please complete the following information):**
 - Python: 3.8.13
 - SCENIC+: 0.1.dev435+g5987737.d20220821
 - Ray 3.8.13

**Comment by cbravo93** [comment]
Hi @BartTheeuwes !

We are not familiar with SLURM, but could you try running in terminal/tmux to check out if it works out of jupyter notebooks? Otherwise here is more info on how to use ray with slurm: https://docs.ray.io/en/latest/cluster/slurm.html

Cheers! 

C

**Comment by BartTheeuwes** [comment]
Hi,

For me it is not working in the normal terminal either. I've already tried to implement the solution from the ray documentation on using SLURM, but this did not seem to solve the problem yet. I will let you know if I find a solution.

All the best,
Bart

**Comment by SeppeDeWinter** [comment]
Hi @BartTheeuwes 

I tried the code in a slurm job.

I think the issue is coming from how you submitted the slurm job. You specify `#SBATCH -n 12` which indicates that you want to start a job with 12 tasks. Our code is not written in a way to use multiple tasks. 
We wrote the code to use multiple cores (within a single task) that's what the `n_cpu` parameter is controlling. 

A solution is to submit a job with a single task: `#SBATCH -n 1` but multiple cores `#SBATCH -c 12`.

See https://groups.google.com/g/slurm-users/c/r_MNRw4gYhQ?pli=1 for a discussion on the difference of the two. 

And from: https://slurm.schedmd.com/sbatch.html
```
-c, --cpus-per-task=<ncpus>
Advise the Slurm controller that ensuing job steps will require ncpus number of processors per task. Without this option, the controller will just try to allocate one processor per task.
For instance, consider an application that has 4 tasks, each requiring 3 processors. If our cluster is comprised of quad-processors nodes and we simply ask for 12 processors, the controller might give us only 3 nodes. However, by using the --cpus-per-task=3 options, the controller knows that each task requires 3 processors on the same node, and the controller will grant an allocation of 4 nodes, one for each of the 4 tasks.
[...]
-n, --ntasks=<number>
sbatch does not launch tasks, it requests an allocation of resources and submits a batch script. This option advises the Slurm controller that job steps run within the allocation will launch a maximum of number tasks and to provide for sufficient resources. The default is one task per node, but note that the --cpus-per-task option will change this default.
```

Using the following command I was able to get a job which allowed ray to work:

```
srun \
   --ntasks=1 \
   -c 18 \
   --time=01:00:00 \
   --partition=dedicated_batch \ #specific to our set up
   --account=dedicated \ #specific to our set up
   --nodelist=r23i27n14  \ #specific to our set up
   --mem 30G \
   --pty bash
```

**Comment by BartTheeuwes** [comment]
Hi Seppe,

Would you be able to paste the full SLURM script? I've tried to copy what you did, but it does not seem to be working for me, maybe I'm missing something. 

I could get Ray to work in a command where I can edit the **kwargs of ray.init(). However not all the functions in SCENIC+ allow for this, like run_scenicplus itself.

**Comment by SeppeDeWinter** [comment]
Hi Bart

I'm not very familiar with SLURM (nor the specific setup you have).

I would guess it would look something like this:

```bash
#!/bin/bash
#SBATCH -p cclake
#SBATCH -A gottgens-sl2-cpu
#SBATCH -N 1
#SBATCH -c 12
```

The **kwargs should indeed be passed when using the `run_scenicplus` function, we will fix this.

For curiosity, which kwargs did you pass that made it work? 

Best,

S

**Comment by BartTheeuwes** [comment]
Hi Seppe,

I tested it only on run_cgs_models, so I'm not sure yet if it will work for other commands as well. I set 
n_cpu=None,
address='auto',
num_gpus=None

**Comment by SeppeDeWinter** [comment]
Hi Bart

By setting n_cpu to None it will actually not use ray at all (it's equivalent to setting n_cpu = 1). 
So this does not actually fix your issue (still only using a single core).

Any luck with SLURM parameters I've sent above?

S

**Comment by BartTheeuwes** [comment]
Hi Seppe,

Even when n_cpu=None, it still requires Ray to work (Unless the function doesn't use Ray when n_cpu=None). 

The way I have it set up now also requires me to set n_cpu=None, and I get the following message if I don't: 
`When connecting to an existing cluster, num_cpus and num_gpus must not be provided.`
However, it is still running in Parallel (I think it detects the number of cores automatically).
For this to work, I do need to pass **kwargs to the function though, specifically I need to have: address='auto', which currently does not work yet for some of the functions that don't take **kwargs.

Here is the complete SLURM script I'm currently using for an interactive Jupyter-notebook session, I will update this if I find out a better way:

`#!/bin/bash
#SBATCH -p cclake #-himem #skylake-himem #icelake #skylake #-himem #cclake
#SBATCH -A gottgens-sl2-cpu
### Modify this according to your Ray workload.
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --tasks-per-node=1
#SBATCH --time 1:00:00
### Modify this according to your Ray workload.
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=5GB
#SBATCH --gpus-per-task=0
### outputs
#SBATCH --output test_notebook-log-%J.txt
#SBATCH --error test_notebook-err-%J.txt

### get/set tunneling info
XDG_RUNTIME_DIR=""
ipnport=$(shuf -i8000-9999 -n1)
ipnip=$(hostname -i)

### print tunneling instructions to jupyter-log-{jobid}.txt
echo -e "
    Copy/Paste this in your local terminal to ssh tunnel with remote
    -----------------------------------------------------------------
    ssh -N -L $ipnport:$ipnip:$ipnport $USER@$SLURM_SUBMIT_HOST.hpc.cam.ac.uk
    -----------------------------------------------------------------

    Then open a browser on your local machine to the following address
    ------------------------------------------------------------------
    localhost:$ipnport  (prefix w/ https:// if using password)
    ------------------------------------------------------------------
    "


# Getting the node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)

head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)


port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "IP Head: $ip_head"
echo -e "
        ssh -N -L $port:$head_node_ip:$port $USER@$SLURM_SUBMIT_HOST.hpc.cam.ac.uk
        "

echo "Starting HEAD at $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" --partition=skylake   --account=gottgens-sl2-cpu \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
    
# optional, though may be useful in certain versions of Ray < 1.0.
sleep 10

# number of nodes other than the head node
worker_num=$((SLURM_JOB_NUM_NODES - 1))

for ((i = 1; i <= worker_num; i++)); do
    node_i=${nodes_array[$i]}
    echo "Starting WORKER $i at $node_i"
    srun --nodes=1 --ntasks=1 -w "$node_i" --partition=skylake   --account=gottgens-sl2-cpu \
        ray start --address "$ip_head" \
        --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
    sleep 5
done

### start an ipcluster instance and launch jupyter server from my container
jupyter-lab --no-browser --port=$ipnport --ip=$ipnip    `

**Comment by BartTheeuwes** [comment]
Hi Seppe,

Thank you for adding **kwargs to the wrappers!

Starting a notebook as you describe does not allow ray to work for me. It says: 
`2022-08-24 10:03:59,736	INFO services.py:1470 -- View the Ray dashboard at http://127.0.0.1:8265/`
Resulting in the same error as in my first post.

That's why in the slurm script I have to start a ray instance, with: 
`srun --nodes=1 --ntasks=1 -w "$head_node" --partition=skylake   --account=gottgens-sl2-cpu \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &`
As  described on https://docs.ray.io/en/master/cluster/vms/user-guides/community/slurm.html

This will allow ray to connect to the IP of the head_node, but only if I set address='auto', n_cpu=None, & num_gpu=None in **kwargs. 
`When connecting to an existing cluster, num_cpus and num_gpus must not be provided.`

I know setting n_cpu=None is not ideal, but currently it's the only way for me to get it to work. When I manually remove the internal check on n_cpu=None, the code runs parallelised.

I know it seems very messy. I will keep trying different things and let you know if I find a way that works without having to set n_cpu=None.

**Comment by SeppeDeWinter** [comment]
Hi Bart

The message `2022-08-24 10:03:59,736 INFO services.py:1470 -- View the Ray dashboard at http://127.0.0.1:8265/` is normal. It's just telling you that ray has successfully started.

Does ray timeout after this?

Which error did you get when you tried starting an interactive session using the srun command (see https://github.com/aertslab/scenicplus/issues/24#issuecomment-1222149794)?

From your previous message I guess it should look something like this in your particular situation

```bash

srun \
   --ntasks=1  \
   -c 12 \
   --time=01:00:00 \
   --partition=skylake \
   --account=gottgens-sl2-cpu 

```

Using multiple nodes (what you're trying to do at the moment) instead of multiple cores is really complicating things and is not really supported by our code (nor tested).   

Best,

S

**Comment by BartTheeuwes** [comment]
Hi Seppe,

Yes Ray times out with the following error message:
`Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup.`

I have tried varying the number of nodes/cores, but that doesn't solve the issue. I think the issue lies in the IP address that Ray tries to connect to. This is why it works for me only when I use the SLURM script I sent above and set address='auto', this allows ray to connect to the IP of the node that the script is running on. 

When I start an interactive session and run the python script from there, I get the exact same error: 
`Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup.`

**Comment by BartTheeuwes** [comment]
For future reference,

This issue occurred because the tmp_dir was not specified correctly. Ray requires an absolute tmp_dir path rather than a relative one. However, my absolute path was too many bytes, resulting in the following error:
`AF_UNIX path length cannot exceed 107 bytes`

This can be circumvented by specifying a shorter tmp_dir path or creating a symlink from the home directory to the tmp_dir, and using the symlink as the tmp_dir path.

**Comment by SeppeDeWinter** [comment]
Hi Bart

Nice. All is working fine now?

Best,

S

**Comment by BartTheeuwes** [comment]
All working great!

**Comment by Lulu0015** [comment]
> I know setting n_cpu=None is not ideal, but currently it's the only way for me to get it to work. When I manually remove the internal check on n_cpu=None, the code runs parallelised.

Hi Bart,

Do you mind explaining how you bypassed the internal check on n_cpu=None to make it run parallelly? I am using the solution you provided above and it's super helpful that it solves the issue of running ray with SLURM for me. But I find the code runs in single core which is super slow.

Thanks,
Lulu

**Comment by BartTheeuwes** [comment]
Hi Lulu,

It turned out that ray actually works fine in SLURM, the only thing that cause a problem for me was the tmp_dir, which has to be set to an absolute path. This solved the whole issue for me. 

As for how to bypass setting n_cpu=None causing SCENIC+ to run on a single core, I don't recommend this. I manually went through some functions to change them to allow ray to work while n_cpu=None, But this is very difficult for some functions, especially the ones where parallelization is most important.

Kind regards,
Bart
