### ISSUE TITLE
How to load results of loom file into SCENIC+ object?

### ISSUE THREAD

**Issue by vckraemer** [aertslab/scenicplus#248]
Hello,

I am very interested in the perturbation tutorial on the mix of melanoma cell lines data. I already found the data on SCope (https://scope.aertslab.org/#/scenic-v2/scenic-v2%2FMM_SCENIC%2B_gene_based.loom/gene) and also found an R package to access the data. But I couldn't find a function or package to load the data into a SCENIC+ object in Python to run only the perturbation tutorial.

Is there either a function or jupyter notebook I didn't find yet to recreate the SCENIC+ object from the tutorial or is there a possibility to directly download it somewhere? I'd rather not want to run the whole tutorial for this data, since I am only interested in the perturbation part of your package.

**Comment by SeppeDeWinter** [comment]
Hi @vckraemer 

You can download the SCENIC+ object from this link: https://cloud.aertslab.org/index.php/s/tdKPMgkfPEz7wLx

Best,

Seppe

**Comment by vckraemer** [comment]
@SeppeDeWinter  thank you very much for providing the object!
