### ISSUE TITLE
Can you restart the pipeline from a given step?

### ISSUE THREAD

**Issue by mason-sweat1** [aertslab/scenicplus#263]
Thanks for the cool package, I am excitedly processing my data and can't wait to see the results. 

I am on the final step, using the wrapper to create scienic plus obj. 

However, I keep having things go wrong. For example, I had the low memory error due to Numba incompatability. 

Is there a way to re-start the pipeline from a particular step? For example, if it crashed on make UMAP, could i just start from that step and work down? Each try takes almost 24 hours due to the number of cells I am integrating, so this would be helpful.

Thanks,
Mason

**Comment by SeppeDeWinter** [comment]
Hi @mason-sweat1 

The results of each step should be saved in your scplus_obj. 
So as long as you still have access to that object (i.e. you saved it to your hard drive), you can recover the progress that has been already made without the need of rerunning the entire pipeline.

In fact, all necessary steps have already been completed if you manage to reach the UMAP generation step.

All the best,

Seppe

**Comment by mason-sweat1** [comment]
Dear Seppe,

I see that now, thank you very much!

I will close this out but had one other question. Could you recommend how to modify the code from the scienicplus_step_by_step protocol so I can perform the UMAP and TSNE?

from scenicplus.dimensionality_reduction import *
run_eRegulons_umap(scplus_obj,
                   scale=True, signature_keys=['Gene_based', 'Region_based'], selected_regulons=scplus_obj.uns['selected_eRegulons']['Gene_based'])
run_eRegulons_tsne(scplus_obj,
                   scale=True, signature_keys=['Gene_based', 'Region_based'], selected_regulons=scplus_obj.uns['selected_eRegulons']['Gene_based'])

My object doesn't have 'selected_eRegulons', I followed the PBMC tutorial from readthedocs with slight modifications to merge samples.

Thanks,
Mason

**Comment by SeppeDeWinter** [comment]
Hi @mason-sweat1 

Happy to help.

No worries!.

All the best,

Seppe
