### ISSUE TITLE
Methods_benchmark

### ISSUE THREAD

**Issue by master-XS** [aertslab/scenicplus#272]
I noticed that the benchmark data for this article is not available on GitHub while I carefully read the paper. [scenicplus_analyses/Benchmarks/SCENIC+/Methods_benchmark.Rmd at main · aertslab/scenicplus_analyses (github.com)](https://github.com/aertslab/scenicplus_analyses/blob/main/Benchmarks/SCENIC%2B/Methods_benchmark.Rmd)
Therefore, I would like to inquire whether you could provide access to this specific dataset?

**Comment by SeppeDeWinter** [comment]
Hi @master-XS 

Please see: https://github.com/aertslab/scenicplus_analyses/issues/1

All the best,

Seppe
