### ISSUE TITLE
Memory efficiency in make_rankings

### ISSUE THREAD

**Issue by schae211** [aertslab/scenicplus#28]
To store the rankings in make_rankings (eregulon_enrichment.py) you initialize a matrix of zeros with datatype np.float64 (double), where np.int32 should work as well and save a lot of memory. I am referring to lines 82-83 (https://github.com/aertslab/scenicplus/blob/1ab4169be5d4c9749c7cb5fec0fe6edee95ea020/src/scenicplus/eregulon_enrichment.py#L82) and 89 (https://github.com/aertslab/scenicplus/blob/1ab4169be5d4c9749c7cb5fec0fe6edee95ea020/src/scenicplus/eregulon_enrichment.py#L89)

**Comment by cbravo93** [comment]
Fixed, thanks for the heads up!

C
