### ISSUE TITLE
Can't install with Python 3.10 - can you provide a container image?

### ISSUE THREAD

**Issue by liz-is** [aertslab/scenicplus#29]
It's not possible to install MACS2 with Python 3.10 at the moment (see [here](https://github.com/macs3-project/MACS/issues/519) and [here](https://github.com/macs3-project/MACS/issues/520)). It's not clear to me exactly how MACS2 is used within SCENIC+ - would it be possible to provide a path to an already-installed MACS2 binary instead of requiring it as a package dependency? (for unfortunate local set-up reasons I can't use Python 3.9, and probably not earlier versions either, as other dependencies fail... I realise this makes this kind of a niche issue)

Alternatively, would it be possible for you to provide a pre-built Docker or Singularity image? I see that you provide instructions for building an image, but we only have Singularity installed on our HPC, not Docker, so I'm not sure if I will be able to run these.

**Comment by cbravo93** [comment]
Hi @liz-is !

There are some options here:

1. You can use our singularity image at https://drive.google.com/file/d/1imm2C9GAb7Fha3MXNmFaydSiutGCbzHJ/view?usp=sharing . However, we have noticed that it may give 'Illegal instruction' errors depending on your system; it would be better if you could compile it yourselve with e.g. podman. But you can give it a try.
2. MACS2 is used to call peaks in pycisTopic. If you are planning to skip this step (using precomputed peaks for example), you can try to clone the pycisTopic repo, remove macs2 from dependencies and install from there. You may find another dependency with issues in this case.
3. In the macs repo some people have already opened issues about python 3.10(https://github.com/macs3-project/MACS/issues/520). They may fix it, hopefully for macs2 and macs3.

Hopefully, some of this solutions may work!

C

**Comment by liz-is** [comment]
Thanks a lot for your quick reply and for the singularity image link! That's super helpful. In the meantime I actually managed to get SCENIC+ to install using Python 3.8 on our system (wasn't expecting it to work!). So I will try that, and if it doesn't work out I'll try your singularity image or building my own.

I hope they will fix the MACS2 install issue quickly - the first report was already a week ago, I'm surprised there's been no response yet given it's so widely used! 🤞

**Comment by cbravo93** [comment]
Hi @liz-is!

Happy that you managed to install it in the end! I will close the issue here for now, but we will keep an eye in the macs2 repo.

Thanks!

C
