### ISSUE TITLE
TypeError export_pseudobulk

### ISSUE THREAD

**Issue by skoturan** [aertslab/scenicplus#298]
**TypeError export_pseudobulk**

I'm trying to run the pycistopic tutorial for 10x multiome data.  I come across the following error when I try to run "export_pseudobulk" :

`TypeError: export_pseudobulk() got an unexpected keyword argument 'remove_duplicates'
`

**Screenshots**
<img width="736" alt="Screenshot 2024-02-08 at 16 24 37" src="https://github.com/aertslab/scenicplus/assets/30719285/7e1ae2fe-c6f8-4007-b177-6730abae12e8">

**Version**
 - Python: 3.8
 - SCENIC+: 1.0.1.dev6+ge5ba6fc.d20240130

Could you please help?
Thanks!

**Comment by laki-spk** [comment]
I am also getting the same error and same version. Could you please help? 
Thank you

**Comment by SeppeDeWinter** [comment]
Hi @laki-spk and @skoturan 

This parameter has been removed as off this PR https://github.com/aertslab/pycisTopic/pull/105.
This part of the code has been optimised and it now always removes duplicates.

You can just run the same code without this parameter.

All the best,

Seppe

**Comment by skoturan** [comment]
Thanks, it worked!
