### ISSUE TITLE
Output scenicplus

### ISSUE THREAD

**Issue by SteveTur** [aertslab/scenicplus#308]
Hi, 

I was wondering how did you manage to plot this kind of output:

![image](https://github.com/aertslab/scenicplus/assets/131205952/338c2025-1436-420b-b237-ded63176d21e)

I tried to look at the code provided by the publications but i couldn't find it.

Thank you for your help.

Best,

Steven

**Comment by SeppeDeWinter** [comment]
Hi @SteveTur 

Unfortunately we don't have an automated function to generate these kind of networks.
To make this we spent a day dragging nodes in Cytoscape.

All the best,

Seppe
