### ISSUE TITLE
AttributeError: ('PyRanges object has no attribute', 'regionID') with create_cistopic_object_from_fragments

### ISSUE THREAD

**Issue by SITRR** [aertslab/scenicplus#316]
Hi!

I'm having an issue that was previously described in [146](https://github.com/aertslab/scenicplus/issues/146). When running the create_cistopic_object_from_fragments with my dataset, I encounter the error AttributeError: ('PyRanges object has no attribute', 'regionID'). @SeppeDeWinter suggested using pandas version 1.5, which I am using but still encountering the same error. 

It's apparent that some of my samples don't pass the QC thresholds based on a FRIP cutoff of 0.4 (I've attached the QC plots). Could these samples be causing the problem? Thanks!

[combined_qc.pdf](https://github.com/aertslab/scenicplus/files/14540491/combined_qc.pdf)

**Comment by SeppeDeWinter** [comment]
Hi @SITRR 

Indeed, if you are retaining not a single barcode from these samples this could cause the issue you are facing.

If you want to exclude these samples entirely from the analysis I would suggest to remove them from the fragment_dict variable.

All the best,

Seppe

**Comment by SITRR** [comment]
@SeppeDeWinter Thank you for getting back to me :) I've excluded those samples and it now runs smoothly!
