### ISSUE TITLE
What is the time complexity of SCENIC+?

### ISSUE THREAD

**Issue by WhenMelancholy** [aertslab/scenicplus#323]
### Discussed in https://github.com/aertslab/scenicplus/discussions/321

<div type='discussions-op-text'>

<sup>Originally posted by **WhenMelancholy** March 12, 2024</sup>
Hello everyone, I am currently running the SCENIC+ data processing pipeline on a small dataset of 3k cells, and this process took several hours. I am curious about the time complexity of SCENIC+ and whether it is linear. I wonder how long it would take to run this algorithm on a dataset with 5M cells. Thank you for your help!</div>

**Comment by SeppeDeWinter** [comment]
Hi @WhenMelancholy 

I answered your question on: https://github.com/aertslab/scenicplus/discussions/321.
Please don't open duplicate issues.

I wish you a nice day.

All the best,

Seppe
