### ISSUE TITLE
hg38_screen_v10_clust.regions_vs_motifs.rankings.feather" is not a cisTarget Feather database in Feather v1 or v2 format

### ISSUE THREAD

**Issue by SITRR** [aertslab/scenicplus#328]
Hi!

I'm at the "Motif enrichment analysis using pycistarget" step of the SCENIC+ "Mix of melanoma cell lines" tutorial, but encountered the following error when running the run_pycistarget function:

"hg38_screen_v10_clust.regions_vs_motifs.rankings.feather" is not a cisTarget Feather database in Feather v1 or v2 format"

I believe I am using the correct version of the database, as I downloaded the hg38_screen_v10_clust.regions_vs_motifs.rankings.feather file yesterday (03/15/2024) from: https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/

Do you know how to fix this problem? Thank you kindly!

Best,
Susana

**Comment by SITRR** [comment]
My apologies, the hg38_screen_v10_clust.regions_vs_motifs.rankings.feather was corrupted. Re-downloading it worked.

**Comment by pinklady789** [comment]
I'm also getting the same error for the mouse feather files: `.../mm10_screen_v10_clust.regions_vs_motifs.rankings.feather" is not a cisTarget Feather database in Feather v1 or v2 format.`

The same goes for the scores.feather file

download from: https://resources.aertslab.org/cistarget/databases/mus_musculus/mm10/screen/mc_v10_clust/region_based/

**Comment by pinklady789** [comment]
re-downloading also solved the issue
