### ISSUE TITLE
Clarification request: what scRNA-seq data is needed to create the SCENIC+ object?

### ISSUE THREAD

**Issue by liz-is** [aertslab/scenicplus#33]
I'm working through the tutorial [here](https://scenicplus.readthedocs.io/en/latest/pbmc_multiome_tutorial.html) but with my own data that was processed with Seurat. 

To facilitate modularity / interoperability, could you give a bit more detail about what data needs to be in the object provided as the `GEX_anndata` argument to `create_SCENICPLUS_object()`? From this line `GEX_anndata = adata.raw.to_adata(),` it looks like you're basically just passing in the original counts, but I haven't worked through the full scanpy processing so I'm not sure. Is there any other data that needs to be included in that object? (normalised data, PCA, etc...)

In general the tutorial is really nice and clear so far. Just for this purpose of interoperability with other tools, it would be super helpful to have a list up top with all the input data needed, so it's all in one place and easy for users to gather the necessary data in the right formats in advance.

**Comment by cbravo93** [comment]
Hi @liz-is !

The only thing you need to provide is the count matrix and the cell data :). We normally use loom files when moving from/to R (ScopeLoomR), you can see an example here: https://scenicplus.readthedocs.io/en/latest/Scenicplus_step_by_step-RTD.html

Cheers!

C

**Comment by liz-is** [comment]
Fab, that's easy then - thanks a lot for the clarification!

**Comment by Umaarasu** [comment]
> Hi @liz-is !
> 
> The only thing you need to provide is the count matrix and the cell data :). We normally use loom files when moving from/to R (ScopeLoomR), you can see an example here: https://scenicplus.readthedocs.io/en/latest/Scenicplus_step_by_step-RTD.html
> 
> Cheers!
> 
> C
Hi, do you have any examples to show how to export scRNA seq from R to Scenic+?

**Comment by Umaarasu** [comment]
> Hi @cbravo93 , do you have any examples to show how to export scRNA seq from R to Scenic+ without involving loom?

**Comment by fahmadimoughari** [comment]
> Hi @liz-is !
> 
> The only thing you need to provide is the count matrix and the cell data :). We normally use loom files when moving from/to R (ScopeLoomR), you can see an example here: https://scenicplus.readthedocs.io/en/latest/Scenicplus_step_by_step-RTD.html
> 
> Cheers!
> 
> C

I need to use my Seurat and Signac objects for scenicplus. But the link that you provided in this comment does not exists anymore. Can you provide the new link?

**Comment by SeppeDeWinter** [comment]
Hi @fahmadimoughari 

You can still find this notebook at this link: https://github.com/aertslab/scenicplus/blob/old/notebooks/Scenicplus_step_by_step-RTD.ipynb

Best,

Seppe
