### ISSUE TITLE
Installation via pip failing due to missing `master` branch in dependency

### ISSUE THREAD

**Issue by henryjburg** [aertslab/scenicplus#336]
**Describe the bug**
When installing via pip using the example in the README, installation fails when attempting to clone [pycisTopic](https://github.com/aertslab/pycisTopic) since it attempts to clone the `master` branch which doesn't exist (I assume it was renamed to `main`?).

**To Reproduce**
`git clone https://github.com/aertslab/scenicplus`
`cd scenicplus`
`pip install -e .`

**Error output**
```
➜  scenicplus git:(main) pip install -e .
Obtaining file:///Users/henry/scenicplus
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting pycisTopic@ git+https://github.com/aertslab/pycisTopic@master (from scenicplus==1.0.1.dev8+g1df154c)
  Cloning https://github.com/aertslab/pycisTopic (to revision master) to /private/var/folders/gr/lvdbk_955pb2blnlcsm4kngc0000gp/T/pip-install-wj50ehw7/pycistopic_d1f2594a93b14effbdbb2360b8af878d
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/pycisTopic /private/var/folders/gr/lvdbk_955pb2blnlcsm4kngc0000gp/T/pip-install-wj50ehw7/pycistopic_d1f2594a93b14effbdbb2360b8af878d
  WARNING: Did not find branch or tag 'master', assuming revision or ref.
  Running command git checkout -q master
  error: pathspec 'master' did not match any file(s) known to git
  error: subprocess-exited-with-error

  × git checkout -q master did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Expected behavior**
Installation should proceed without errors, I believe when I was using this about a week ago it was fine.

**Version (please complete the following information):**
 - Python: 3.8
 - SCENIC+: latest (commit: 1df154ce6ea93d634a6c2ec88362a473587422eb)
 - pycisTopic: latest (commit: e5d5f19c941c7416628a80c846848eb49c3167b9)

**Additional context**
* I think the default branch was renamed to `main` in the pycisTopic repo.

**Comment by henryjburg** [comment]
Changing the line:
`git+https://github.com/aertslab/pycisTopic@master#egg=pycisTopic`
to:
`git+https://github.com/aertslab/pycisTopic@main#egg=pycisTopic`
in `requirements.txt` seems to resolve this, but would be good to confirm.

**Comment by SeppeDeWinter** [comment]
Hi @henryjburg 

Yes, that's correct. I forgot to change it.
Should be fixed now https://github.com/aertslab/scenicplus/commit/bca365b0a662e10e215e66dfa32f7505e661e25f.

I highly recommend to use the development branch of SCENIC+ though, this will soon become the default code. It's a lot easier to use and a lot more efficient. Tutorials are also online: https://scenicplus.readthedocs.io/en/development/tutorials.html

All the best,

Seppe
