### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by m03077yhtnt** [aertslab/scenicplus#338]
**Describe the bug**
I am having the trouble to install scenic+, although I have spent a considerable amount of time trying to do so. I would greatly appreciate it if you could provide any solutions or assistance.
”× Getting requirements to build wheel did not run successfully.”
The same error messages come out even though the python version is 3.8.

**To Reproduce**
The error comes out once I wrote the command, "pip install .".
$ conda create --name scenicplus python=3.11 -y
$ conda activate scenicplus
$ git clone https://github.com/aertslab/scenicplus
$ cd scenicplus
$ git checkout development
$ pip install .

**Version (please complete the following information):**
 - Python: [Python 3.11.8]

**Error output**
(scenicplus) C:\Users \Desktop\scenicplus>pip install .
Processing c:\users\ desktop\scenicplus
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting loomxpy@ git+https://github.com/aertslab/LoomXpy@main (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/LoomXpy (to revision main) to c:\users\m03077yh\appdata\local\temp\pip-install-hrl49sqb\loomxpy_118888ee8aa8459ca64f7e6d0b6505d4
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/LoomXpy 'C:\Users\m03077yh\AppData\Local\Temp\pip-install-hrl49sqb\loomxpy_118888ee8aa8459ca64f7e6d0b6505d4'
  Resolved https://github.com/aertslab/LoomXpy to commit 61995ff10940968eac2cee8fe48300ab477a15d0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycistarget@ git+https://github.com/aertslab/pycistarget@development (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/pycistarget (to revision development) to c:\users\m03077yh\appdata\local\temp\pip-install-hrl49sqb\pycistarget_18ee763c57b64de99d4a69fc8578d246
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/pycistarget 'C:\Users\m03077yh\AppData\Local\Temp\pip-install-hrl49sqb\pycistarget_18ee763c57b64de99d4a69fc8578d246'
  Running command git checkout -b development --track origin/development
  branch 'development' set up to track 'origin/development'.
  Switched to a new branch 'development'
  Resolved https://github.com/aertslab/pycistarget to commit c6591ca8bcf1a1e95ec7e2ee432199df87c8e21f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycistopic@ git+https://github.com/aertslab/pycisTopic (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/pycisTopic to c:\users\m03077yh\appdata\local\temp\pip-install-hrl49sqb\pycistopic_4481ced0582849919abaabed471fcdb2
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/pycisTopic 'C:\Users\m03077yh\AppData\Local\Temp\pip-install-hrl49sqb\pycistopic_4481ced0582849919abaabed471fcdb2'
  Resolved https://github.com/aertslab/pycisTopic to commit e5d5f19c941c7416628a80c846848eb49c3167b9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyscenic@ git+https://github.com/aertslab/pySCENIC@master (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/pySCENIC (to revision master) to c:\users\m03077yh\appdata\local\temp\pip-install-hrl49sqb\pyscenic_3bd89ee580b242228e42f1c517a512fd
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/pySCENIC 'C:\Users\m03077yh\AppData\Local\Temp\pip-install-hrl49sqb\pyscenic_3bd89ee580b242228e42f1c517a512fd'
  Resolved https://github.com/aertslab/pySCENIC to commit 1cd059f12c499b968dacd206b1dfaa1412709b3e
  Preparing metadata (setup.py) ... done
Collecting adjusttext==1.0.4 (from scenicplus==1.0a1)
  Using cached adjustText-1.0.4-py3-none-any.whl.metadata (3.0 kB)
Collecting aiohttp==3.9.3 (from scenicplus==1.0a1)
  Using cached aiohttp-3.9.3-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting aiosignal==1.3.1 (from scenicplus==1.0a1)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting anndata==0.10.5.post1 (from scenicplus==1.0a1)
  Using cached anndata-0.10.5.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting annoy==1.17.3 (from scenicplus==1.0a1)
  Using cached annoy-1.17.3.tar.gz (647 kB)
  Preparing metadata (setup.py) ... done
Collecting appdirs==1.4.4 (from scenicplus==1.0a1)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting arboreto==0.1.6 (from scenicplus==1.0a1)
  Using cached arboreto-0.1.6-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting argparse-dataclass==2.0.0 (from scenicplus==1.0a1)
  Using cached argparse_dataclass-2.0.0-py3-none-any.whl.metadata (7.2 kB)
Collecting array-api-compat==1.5.1 (from scenicplus==1.0a1)
  Using cached array_api_compat-1.5.1-py3-none-any.whl.metadata (1.3 kB)
Collecting asttokens==2.4.1 (from scenicplus==1.0a1)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting attr==0.3.2 (from scenicplus==1.0a1)
  Using cached attr-0.3.2-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting attrs==23.2.0 (from scenicplus==1.0a1)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting bbknn==1.6.0 (from scenicplus==1.0a1)
  Using cached bbknn-1.6.0-py3-none-any.whl.metadata (8.2 kB)
Collecting beautifulsoup4==4.12.3 (from scenicplus==1.0a1)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bidict==0.23.1 (from scenicplus==1.0a1)
  Using cached bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Collecting bioservices==1.11.2 (from scenicplus==1.0a1)
  Using cached bioservices-1.11.2.tar.gz (191 kB)
  Preparing metadata (setup.py) ... done
Collecting blosc2==2.5.1 (from scenicplus==1.0a1)
  Using cached blosc2-2.5.1-cp311-cp311-win_amd64.whl.metadata (9.4 kB)
Collecting bokeh==3.4.0 (from scenicplus==1.0a1)
  Using cached bokeh-3.4.0-py3-none-any.whl.metadata (12 kB)
Collecting boltons==23.1.1 (from scenicplus==1.0a1)
  Using cached boltons-23.1.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting bs4==0.0.2 (from scenicplus==1.0a1)
  Using cached bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting cattrs==23.2.3 (from scenicplus==1.0a1)
  Using cached cattrs-23.2.3-py3-none-any.whl.metadata (10 kB)
Collecting certifi==2024.2.2 (from scenicplus==1.0a1)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.2 (from scenicplus==1.0a1)
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting click==8.1.7 (from scenicplus==1.0a1)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cloudpickle==3.0.0 (from scenicplus==1.0a1)
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting colorama==0.4.6 (from scenicplus==1.0a1)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting colorlog==6.8.2 (from scenicplus==1.0a1)
  Using cached colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Collecting conda-inject==1.3.1 (from scenicplus==1.0a1)
  Using cached conda_inject-1.3.1-py3-none-any.whl.metadata (855 bytes)
Collecting configargparse==1.7 (from scenicplus==1.0a1)
  Using cached ConfigArgParse-1.7-py3-none-any.whl.metadata (23 kB)
Collecting connection-pool==0.0.3 (from scenicplus==1.0a1)
  Using cached connection_pool-0.0.3.tar.gz (3.8 kB)
  Preparing metadata (setup.py) ... done
Collecting contourpy==1.2.0 (from scenicplus==1.0a1)
  Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
Collecting ctxcore==0.2.0 (from scenicplus==1.0a1)
  Using cached ctxcore-0.2.0-py3-none-any.whl.metadata (3.1 kB)
Collecting cycler==0.12.1 (from scenicplus==1.0a1)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting cython==0.29.37 (from scenicplus==1.0a1)
  Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting cytoolz==0.12.3 (from scenicplus==1.0a1)
  Using cached cytoolz-0.12.3-cp311-cp311-win_amd64.whl.metadata (4.7 kB)
Collecting dask==2024.2.1 (from dask[array,complete,dataframe,diagnostics,distributed]==2024.2.1->scenicplus==1.0a1)
  Using cached dask-2024.2.1-py3-none-any.whl.metadata (3.7 kB)
Collecting dataclasses-json==0.6.4 (from scenicplus==1.0a1)
  Using cached dataclasses_json-0.6.4-py3-none-any.whl.metadata (25 kB)
Collecting datrie==0.8.2 (from scenicplus==1.0a1)
  Using cached datrie-0.8.2.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting decorator==5.1.1 (from scenicplus==1.0a1)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting dill==0.3.8 (from scenicplus==1.0a1)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting distributed==2024.2.1 (from scenicplus==1.0a1)
  Using cached distributed-2024.2.1-py3-none-any.whl.metadata (3.4 kB)
Collecting docutils==0.20.1 (from scenicplus==1.0a1)
  Using cached docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting dpath==2.1.6 (from scenicplus==1.0a1)
  Using cached dpath-2.1.6-py3-none-any.whl.metadata (15 kB)
Collecting easydev==0.13.1 (from scenicplus==1.0a1)
  Using cached easydev-0.13.1-py3-none-any.whl.metadata (3.5 kB)
Collecting et-xmlfile==1.1.0 (from scenicplus==1.0a1)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Collecting executing==2.0.1 (from scenicplus==1.0a1)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting fastjsonschema==2.19.1 (from scenicplus==1.0a1)
  Using cached fastjsonschema-2.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting fbpca==1.0 (from scenicplus==1.0a1)
  Using cached fbpca-1.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting filelock==3.13.1 (from scenicplus==1.0a1)
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting fonttools==4.50.0 (from scenicplus==1.0a1)
  Using cached fonttools-4.50.0-cp311-cp311-win_amd64.whl.metadata (162 kB)
Collecting frozendict==2.4.0 (from scenicplus==1.0a1)
  Using cached frozendict-2.4.0.tar.gz (314 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frozenlist==1.4.1 (from scenicplus==1.0a1)
  Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting fsspec==2024.3.1 (from scenicplus==1.0a1)
  Using cached fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting future==1.0.0 (from scenicplus==1.0a1)
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting gensim==4.3.2 (from scenicplus==1.0a1)
  Using cached gensim-4.3.2-cp311-cp311-win_amd64.whl.metadata (8.5 kB)
Collecting geosketch==1.2 (from scenicplus==1.0a1)
  Using cached geosketch-1.2-py3-none-any.whl.metadata (406 bytes)
Collecting gevent==24.2.1 (from scenicplus==1.0a1)
  Using cached gevent-24.2.1-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting gitdb==4.0.11 (from scenicplus==1.0a1)
  Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
Collecting gitpython==3.1.42 (from scenicplus==1.0a1)
  Using cached GitPython-3.1.42-py3-none-any.whl.metadata (12 kB)
Collecting globre==0.1.5 (from scenicplus==1.0a1)
  Using cached globre-0.1.5.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting greenlet==3.0.3 (from scenicplus==1.0a1)
  Using cached greenlet-3.0.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting grequests==0.7.0 (from scenicplus==1.0a1)
  Using cached grequests-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting gseapy==0.10.8 (from scenicplus==1.0a1)
  Using cached gseapy-0.10.8-py3-none-any.whl.metadata (11 kB)
Collecting h5py==3.10.0 (from scenicplus==1.0a1)
  Using cached h5py-3.10.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting harmonypy==0.0.9 (from scenicplus==1.0a1)
  Using cached harmonypy-0.0.9-py3-none-any.whl.metadata (3.7 kB)
Collecting humanfriendly==10.0 (from scenicplus==1.0a1)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting idna==3.6 (from scenicplus==1.0a1)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting igraph==0.11.4 (from scenicplus==1.0a1)
  Using cached igraph-0.11.4-cp39-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting imageio==2.34.0 (from scenicplus==1.0a1)
  Using cached imageio-2.34.0-py3-none-any.whl.metadata (4.9 kB)
Collecting immutables==0.20 (from scenicplus==1.0a1)
  Using cached immutables-0.20-cp311-cp311-win_amd64.whl.metadata (4.7 kB)
Collecting importlib-metadata==7.0.1 (from scenicplus==1.0a1)
  Using cached importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting importlib-resources==6.1.2 (from scenicplus==1.0a1)
  Using cached importlib_resources-6.1.2-py3-none-any.whl.metadata (3.9 kB)
Collecting interlap==0.2.7 (from scenicplus==1.0a1)
  Using cached interlap-0.2.7.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... done
Collecting intervaltree==3.1.0 (from scenicplus==1.0a1)
  Using cached intervaltree-3.1.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting ipython==8.22.2 (from scenicplus==1.0a1)
  Using cached ipython-8.22.2-py3-none-any.whl.metadata (4.8 kB)
Collecting jedi==0.19.1 (from scenicplus==1.0a1)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting jinja2==3.1.3 (from scenicplus==1.0a1)
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting joblib==1.3.2 (from scenicplus==1.0a1)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting jsonpickle==3.0.3 (from scenicplus==1.0a1)
  Using cached jsonpickle-3.0.3-py3-none-any.whl.metadata (7.3 kB)
Collecting jsonschema==4.21.1 (from scenicplus==1.0a1)
  Using cached jsonschema-4.21.1-py3-none-any.whl.metadata (7.8 kB)
Collecting jsonschema-specifications==2023.12.1 (from scenicplus==1.0a1)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting jupyter-core==5.7.2 (from scenicplus==1.0a1)
  Using cached jupyter_core-5.7.2-py3-none-any.whl.metadata (3.4 kB)
Collecting kaleido==0.2.1 (from scenicplus==1.0a1)
  Using cached kaleido-0.2.1-py2.py3-none-win_amd64.whl.metadata (15 kB)
Collecting kiwisolver==1.4.5 (from scenicplus==1.0a1)
  Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Collecting lazy-loader==0.3 (from scenicplus==1.0a1)
  Using cached lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting lda==3.0.0 (from scenicplus==1.0a1)
  Using cached lda-3.0.0-cp311-cp311-win_amd64.whl.metadata (7.7 kB)
Collecting leidenalg==0.10.2 (from scenicplus==1.0a1)
  Using cached leidenalg-0.10.2-cp38-abi3-win_amd64.whl.metadata (10 kB)
Collecting line-profiler==4.1.2 (from scenicplus==1.0a1)
  Using cached line_profiler-4.1.2-cp311-cp311-win_amd64.whl.metadata (32 kB)
Collecting llvmlite==0.42.0 (from scenicplus==1.0a1)
  Using cached llvmlite-0.42.0-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting locket==1.0.0 (from scenicplus==1.0a1)
  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting loompy==3.0.7 (from scenicplus==1.0a1)
  Using cached loompy-3.0.7.tar.gz (4.8 MB)
  Preparing metadata (setup.py) ... done
Collecting lxml==5.1.0 (from scenicplus==1.0a1)
  Using cached lxml-5.1.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting lz4==4.3.3 (from scenicplus==1.0a1)
  Using cached lz4-4.3.3-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting macs2==2.2.9.1 (from scenicplus==1.0a1)
  Using cached MACS2-2.2.9.1.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting markdown-it-py==3.0.0 (from scenicplus==1.0a1)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting markupsafe==2.1.5 (from scenicplus==1.0a1)
  Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting marshmallow==3.21.1 (from scenicplus==1.0a1)
  Using cached marshmallow-3.21.1-py3-none-any.whl.metadata (7.2 kB)
Collecting matplotlib==3.6.3 (from scenicplus==1.0a1)
  Using cached matplotlib-3.6.3-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting matplotlib-inline==0.1.6 (from scenicplus==1.0a1)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl.metadata (2.8 kB)
Collecting mdurl==0.1.2 (from scenicplus==1.0a1)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting mizani==0.9.3 (from scenicplus==1.0a1)
  Using cached mizani-0.9.3-py3-none-any.whl.metadata (4.6 kB)
Collecting msgpack==1.0.8 (from scenicplus==1.0a1)
  Using cached msgpack-1.0.8-cp311-cp311-win_amd64.whl.metadata (9.4 kB)
Collecting mudata==0.2.3 (from scenicplus==1.0a1)
  Using cached mudata-0.2.3-py3-none-any.whl.metadata (4.7 kB)
Collecting multidict==6.0.5 (from scenicplus==1.0a1)
  Using cached multidict-6.0.5-cp311-cp311-win_amd64.whl.metadata (4.3 kB)
Collecting multiprocessing-on-dill==3.5.0a4 (from scenicplus==1.0a1)
  Using cached multiprocessing_on_dill-3.5.0a4.tar.gz (53 kB)
  Preparing metadata (setup.py) ... done
Collecting mypy-extensions==1.0.0 (from scenicplus==1.0a1)
  Using cached mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting natsort==8.4.0 (from scenicplus==1.0a1)
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting nbformat==5.10.3 (from scenicplus==1.0a1)
  Using cached nbformat-5.10.3-py3-none-any.whl.metadata (3.6 kB)
Collecting ncls==0.0.68 (from scenicplus==1.0a1)
  Using cached ncls-0.0.68-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
Collecting ndindex==1.8 (from scenicplus==1.0a1)
  Using cached ndindex-1.8-py3-none-any.whl.metadata (3.4 kB)
Collecting networkx==3.2.1 (from scenicplus==1.0a1)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting numba==0.59.0 (from scenicplus==1.0a1)
  Using cached numba-0.59.0-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting numexpr==2.9.0 (from scenicplus==1.0a1)
  Using cached numexpr-2.9.0-cp311-cp311-win_amd64.whl.metadata (8.1 kB)
Collecting numpy==1.26.4 (from scenicplus==1.0a1)
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting numpy-groupies==0.10.2 (from scenicplus==1.0a1)
  Using cached numpy_groupies-0.10.2-py3-none-any.whl.metadata (18 kB)
Collecting openpyxl==3.1.2 (from scenicplus==1.0a1)
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting packaging==24.0 (from scenicplus==1.0a1)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pandas==1.5.0 (from scenicplus==1.0a1)
  Using cached pandas-1.5.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting parso==0.8.3 (from scenicplus==1.0a1)
  Using cached parso-0.8.3-py2.py3-none-any.whl.metadata (7.5 kB)
Collecting partd==1.4.1 (from scenicplus==1.0a1)
  Using cached partd-1.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting patsy==0.5.6 (from scenicplus==1.0a1)
  Using cached patsy-0.5.6-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting pexpect==4.9.0 (from scenicplus==1.0a1)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pillow==10.2.0 (from scenicplus==1.0a1)
  Using cached pillow-10.2.0-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting plac==1.4.3 (from scenicplus==1.0a1)
  Using cached plac-1.4.3-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting platformdirs==4.2.0 (from scenicplus==1.0a1)
  Using cached platformdirs-4.2.0-py3-none-any.whl.metadata (11 kB)
Collecting plotly==5.19.0 (from scenicplus==1.0a1)
  Using cached plotly-5.19.0-py3-none-any.whl.metadata (7.0 kB)
Collecting plotnine==0.12.4 (from scenicplus==1.0a1)
  Using cached plotnine-0.12.4-py3-none-any.whl.metadata (8.9 kB)
Collecting polars==0.20.13 (from scenicplus==1.0a1)
  Using cached polars-0.20.13-cp38-abi3-win_amd64.whl.metadata (15 kB)
Collecting progressbar2==4.4.2 (from scenicplus==1.0a1)
  Using cached progressbar2-4.4.2-py3-none-any.whl.metadata (17 kB)
Collecting prompt-toolkit==3.0.43 (from scenicplus==1.0a1)
  Using cached prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting protobuf==5.26.0 (from scenicplus==1.0a1)
  Using cached protobuf-5.26.0-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting psutil==5.9.8 (from scenicplus==1.0a1)
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting ptyprocess==0.7.0 (from scenicplus==1.0a1)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting pulp==2.8.0 (from scenicplus==1.0a1)
  Using cached PuLP-2.8.0-py3-none-any.whl.metadata (5.4 kB)
Collecting pure-eval==0.2.2 (from scenicplus==1.0a1)
  Using cached pure_eval-0.2.2-py3-none-any.whl.metadata (6.2 kB)
Collecting py-cpuinfo==9.0.0 (from scenicplus==1.0a1)
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
Collecting pyarrow==15.0.0 (from scenicplus==1.0a1)
  Using cached pyarrow-15.0.0-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting pyarrow-hotfix==0.6 (from scenicplus==1.0a1)
  Using cached pyarrow_hotfix-0.6-py3-none-any.whl.metadata (3.6 kB)
Collecting pybedtools==0.9.1 (from scenicplus==1.0a1)
  Using cached pybedtools-0.9.1.tar.gz (12.5 MB)
  Preparing metadata (setup.py) ... done
Collecting pybigtools==0.1.2 (from scenicplus==1.0a1)
  Using cached pybigtools-0.1.2-cp311-none-win_amd64.whl.metadata (1.3 kB)
Collecting pybigwig==0.3.22 (from scenicplus==1.0a1)
  Using cached pyBigWig-0.3.22.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\m03077yh\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\m03077yh\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users \AppData\Local\Temp\pip-build-env-czv4kqu0\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users \AppData\Local\Temp\pip-build-env-czv4kqu0\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users \AppData\Local\Temp\pip-build-env-czv4kqu0\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SeppeDeWinter** [comment]
Hi @m03077yhtnt 

Not sure what is going wrong here.
For your outputs I see that you are trying to install the code on a windows machine? 

We have never tried this, could you try again in a linux environment?

All the best,

Seppe

**Comment by m03077yhtnt** [comment]
Thank you so much for your response. I tried to install the code on anaconda environment using my windows machine. According to your advice, I changed from anaconda to Ubuntu or WSL. Then, it has been achieved. Thank you so much for your advice.
Sincerely,
Yu

**Comment by SeppeDeWinter** [comment]
No worries!

Good luck with the analyses
