### ISSUE TITLE
Provide files used for tutorial SCENIC+ step-by-step in the human cerebellum

### ISSUE THREAD

**Issue by chrarnold** [aertslab/scenicplus#35]
I am following the tutorial SCENIC+ step-by-step in the human cerebellum, and I dont see where the linked file 
`/staging/leuven/stg_00002/lcb/cbravo/Multiomics_pipeline/analysis/10x_multiome_brain/output/atac/pycistopic/DARs/Imputed_accessibility.pkl`is available anywhere. The same goes for `/staging/leuven/stg_00002/lcb/cbravo/Multiomics_pipeline/analysis/10x_multiome_brain/output/atac/pycistopic/10x_multiome_brain_cisTopicObject_noDBL.pkl`, `/staging/leuven/stg_00002/lcb/cbravo/Multiomics_pipeline/analysis/10x_multiome_brain/output/rna/seurat/10x_multiome_brain_Seurat.loom`, and the various files within `/staging/leuven/stg_00002/lcb/cbravo/Multiomics_pipeline/analysis/10x_multiome_brain/output/atac/pycistarget/`.

Alternatively, the SCENIC+ object could be made available so one can start from there, maybe?

Is it possible to provide these files somewhere so the vignette can be followed directly, have I overseen it?
Thanks!

**Comment by cbravo93** [comment]
Hi @chrarnold !

I have put the SCENIC+ object here (it has the complete analysis, it is big!): https://drive.google.com/file/d/1YdEc6eSR4QhzQ1xx13ASSQ9cKzKfT5l_/view?usp=sharing  . You can also generate those files yourself running the whole SCENIC+ workflow,  following the pycisTopic (https://pycistopic.readthedocs.io/en/latest/Single_sample_workflow-RTD.html) and pycistarget (https://pycistarget.readthedocs.io/en/latest/pycistarget_scenic%2B_human_brain.html) tutorials. If you want to query regulons or visualize the data, you can take a look in https://scope.aertslab.org/#/scenic-v2/ (under 10x_multiome_brain).

Cheers!

C

**Comment by chrarnold** [comment]
Thanks a lot for the super-quick reply and the link! Appreciated, cheers!

**Comment by bitcometz** [comment]
hello, I also want those files  to run SCENIC+ because I failed at pycisTopic with peak calling.

But I can not open the URL:

https://drive.google.com/file/d/1YdEc6eSR4QhzQ1xx13ASSQ9cKzKfT5l_/view?usp=sharing 

Could you please help with this problem ?

Thanks !!!

**Comment by dcolinmorgan** [comment]
yes the drive link is dead -- might you consider making it available again? @cbravo93 @ghuls @aertslab

**Comment by SeppeDeWinter** [comment]
Hi @dcolinmorgan 

Would you mind sending me an email (seppe.dewinter@kuleuven.be). I will send you a new download link.

Best,

Seppe
