### ISSUE TITLE
Plotting the eRegulon enrichment score using the scanpy umap function [development branch]

### ISSUE THREAD

**Issue by zfliu01** [aertslab/scenicplus#351]
Hi Seppe,

It seems like when plotting the eRegulon enrichment score using the scanpy umap function will result in this error. It does look like it is a scanpy error instead of scenicplus itself.

>>> sc.pl.umap(eRegulon_gene_AUC, color = "scRNA_counts:GROUP")
/home/zfliu01/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scanpy/plotting/_tools/scatterplots.py:378: UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored
  cax = scatter(
>>> sc.pl.umap(eRegulon_gene_AUC, color = "scRNA_counts:sample")
/home/zfliu01/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scanpy/plotting/_tools/scatterplots.py:378: UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored
  cax = scatter(
>>> sc.pl.umap(eRegulon_gene_AUC, color = "scRNA_counts:RNA_snn_res.0.5")
/home/zfliu01/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scanpy/plotting/_tools/scatterplots.py:378: UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored
  cax = scatter(
>>>>
>>>>

**Version (please complete the following information):**
 - Python: 3.11.8
 - SCENIC+: 1.0a1
 - scanpy : 1.8.2
 - matplotlib : 3.6.3

Please let me know if anything else is needed.

Thank you!
Jeff

**Comment by SeppeDeWinter** [comment]
Hi,

Yes this seems to be a scanpy issue, see https://github.com/scverse/scanpy/issues/2411.

All the best,

Seppe

**Comment by zfliu01** [comment]
Just realized that since I'm using our cluster unless I specify save path I'm not getting graphical output... After setting that I'm seeing figures.

Sorry for the confusion,
Jeff
