### ISSUE TITLE
Installation issue (scenicplus and pyscenic conflicting dependencies)

### ISSUE THREAD

**Issue by Daliya-K** [aertslab/scenicplus#354]
Hi, 
Thank you for the great package!

I am trying to install scenicplus on an Ubuntu desktop using the following code:

**Code**
`conda create --name scenicplus python=3.8`
`conda activate scenicplus`
`git clone https://github.com/aertslab/scenicplus`
`cd scenicplus`
`pip install -e .`

**Error**

> × Preparing metadata (pyproject.toml) did not run successfully.  
  │ exit code: 1 <br />
  ╰─> [4 lines of output] <br />
      Requirement already satisfied: numpy>=1.17 in /tmp/pip-build-env-w55f15aj/overlay/lib/python3.8/site-packages (1.24.4)   
      error in MACS2 setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)   
          numpy>=>=1.17

So I followed the instructions from https://github.com/aertslab/scenicplus/issues/101: 

**Code**
`cd ..`
`wget https://github.com/macs3-project/MACS/archive/refs/tags/v2.2.7.1.tar.gz -O MACS.tar.gz`
`tar -xvf MACS.tar.gz`
`cd MACS-2.2.7.1`
`sed -i 's/install_requires = \[f"numpy>={numpy_requires}",\]/install_requires = \[f"numpy{numpy_requires}",\]/' setup.py`
`pip install -e .`

**Error**

> Error compiling Cython file:
          crick_right = right_sum(crick, search_start, window_size)
        wtd_list = np.zeros( search_end - search_start + 1, dtype="float32")
          i = 0
          for j in range(search_start, search_end+1):
              wtd_list[i] = max((2 * (watson_left * crick_right)**0.5 - watson_right - crick_left),0) # minimum score is 0
    
    
Then I tried to install MACS2 with pip, which ran successfully
`pip install MACS2`

> Successfully installed Cython-0.29.37 MACS2-2.2.9.1 numpy-1.24.4

But then, when I tried to install scenicplus again, I  still got an error

**Code**

`cd scenicplus`
`pip install -e .`

**Error**
>  ERROR: Cannot install scenicplus and scenicplus==1.0.1.dev11+gf1756c1 because these package versions have conflicting dependencies.
   The conflict is caused by:
    scenicplus 1.0.1.dev11+gf1756c1 depends on ctxcore
    pyscenic 0.12.1+8.gd2309fe depends on ctxcore>=0.2.0

I have also tried the isntallation using  Docker/Singularity, but still no success:

**Code**
`git clone https://github.com/aertslab/pycisTopic.git`
`git clone https://github.com/aertslab/pycistarget.git`
`git clone https://github.com/aertslab/scenicplus.git`
`podman login docker.io`
`podman build -t aertslab/scenicplus:latest . -f scenicplus/Dockerfile`

**Error**

> ERROR: Package 'pycistopic' requires a different Python: 3.8.19 not in '~=3.11'
[2/2] STEP 1/6: FROM python:3.8-slim AS build-image
Error: error building at STEP "RUN cd /tmp/pycisTopic &&      pip install . &&      cd .. && rm -rf pycisTopic": error while running runtime: exit status 1

I don't understand this error, as the Python in this environment is 3.8, not 3.11....

Would really appreciate some help with this!

Best,
Daliya

**Comment by SeppeDeWinter** [comment]
Hi @Daliya-K 

I would strongly suggest to install the development branch of SCENIC+.

See: https://github.com/aertslab/scenicplus/tree/development

All the best.

Seppe

**Comment by AnastasiiaKorosteleva** [comment]
Hi! I face the same problem as mentioned above and tried [scenicplus/tree/development](https://github.com/aertslab/scenicplus/tree/development), but having another problem: 


INFO: pip is looking at multiple versions of scenicplus to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.10.0 Requires-Python >=3.9; 0.10.0rc1 Requires-Python >=3.9; 0.10.1 Requires-Python >=3.9; 0.10.2 Requires-Python >=3.9; 0.10.3 Requires-Python >=3.9; 0.10.4 Requires-Python >=3.9; 0.10.5 Requires-Python >=3.9; 0.10.5.post1 Requires-Python >=3.9; 0.10.6 Requires-Python >=3.9; 0.10.7 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement anndata==0.10.5.post1 (from scenicplus) (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.3.0.1, 0.3.0.2, 0.3.0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.8.post1, 0.5.9, 0.5.10, 0.5.10.post1, 0.5.10.post2, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.6.14, 0.6.15, 0.6.16, 0.6.17, 0.6.18, 0.6.19, 0.6.20, 0.6.21, 0.6.22rc1, 0.6.22, 0.6.22.post1, 0.7rc1, 0.7rc2, 0.7, 0.7.1, 0.7.2a1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0rc1, 0.8.0, 0.9.0rc1, 0.9.0, 0.9.1, 0.9.2)
ERROR: No matching distribution found for anndata==0.10.5.post1

**Comment by AnastasiiaKorosteleva** [comment]
Thank you Seppe, development branch of SCENIC+ has successfully installed.
