### ISSUE TITLE
run_scenicplus hanging

### ISSUE THREAD

**Issue by yupingz** [aertslab/scenicplus#36]
Hi, 
My scenicplus run seems to hang for a while, any suggestion what I should do? Below are my command and last few lines of message. 
from scenicplus.wrappers.run_scenicplus import run_scenicplus
try:
    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['GEX_celltype'],
        species = 'mmusculus',
        assembly = 'mm10',
        tf_file = 'allTFs_mm.txt',
        save_path =  'scenicplus',
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = True,
        path_bedToBigBed = '/mctp/share/users/yupingz/tools/',
        n_cpu = 12,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill'))
except Exception as e:
    #in case of failure, still save the object
    dill.dump(scplus_obj, open('scenicplus/scplus_obj.pkl', 'wb'), protocol=-1)
    raise(e)

##########################################
022-09-19 04:19:28,716	WARNING services.py:1882 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67100672 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2022-09-19 04:19:32,119	INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [23:47<00:00, 101.97s/it]
2022-09-19 04:43:23,234 GSEA         INFO     Subsetting TF2G adjacencies for TF with motif.                                                                                             
2022-09-19 04:43:35,257	WARNING services.py:1882 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67100672 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2022-09-19 04:43:39,455	INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
2022-09-19 04:43:40,380 GSEA         INFO     Running GSEA...
initializing:   0%|                                                                                                                                 | 15/22043 [00:06<2:40:25,  2.29it/s](_ray_run_gsea_for_e_module pid=247665) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in true_divide
(_ray_run_gsea_for_e_module pid=247665)   norm_tag =  1.0/sum_correl_tag
(_ray_run_gsea_for_e_module pid=247665) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
(_ray_run_gsea_for_e_module pid=247665)   RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
initializing:   0%|                                                                                                                                 | 21/22043 [00:09<2:59:16,  2.05it/s](_ray_run_gsea_for_e_module pid=247658) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in true_divide
(_ray_run_gsea_for_e_module pid=247658)   norm_tag =  1.0/sum_correl_tag
(_ray_run_gsea_for_e_module pid=247658) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
(_ray_run_gsea_for_e_module pid=247658)   RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
initializing:   0%|▏                                                                                                                                | 23/22043 [00:10<2:52:50,  2.12it/s](_ray_run_gsea_for_e_module pid=247661) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in true_divide
(_ray_run_gsea_for_e_module pid=247661)   norm_tag =  1.0/sum_correl_tag
(_ray_run_gsea_for_e_module pid=247661) /opt/venv/lib/python3.8/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
(_ray_run_gsea_for_e_module pid=247661)   RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
initializing:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 18689/22043 [18:51<01:09, 48.10it/s](raylet) Spilled 3791 MiB, 9979 objects, write throughput 966 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
initializing:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 18796/22043 [18:52<00:33, 97.48it/s](raylet) Spilled 7001 MiB, 18433 objects, write throughput 1480 MiB/s.
initializing:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 19594/22043 [19:54<03:35, 11.36it/s](raylet) Spilled 8213 MiB, 21535 objects, write throughput 1311 MiB/s.
initializing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22043/22043 [23:22<00:00, 15.72it/s]
Running using 12 cores:  32%|████████████████████████████████████▏                                                                           | 7202/22299 [3:44:32<713:05:46, 170.04s/it]

**Comment by SeppeDeWinter** [comment]
Hi

From the spill messages from ray (e.g. `Spilled 8213 MiB, 21535 objects, write throughput 1311 MiB/s.`) it seems like your memory is full. Do you have an idea how much memory was being used (and how much was available) during this run. 

Also the part of the workflow that did manage to finish should be stored in the object already, so please make sure to load the object again (`scplus_obj = dill.load(open(`scenicplus/scplus_obj.pkl', 'rb'))`) before running again.

**Comment by yupingz** [comment]
Thank you for pointing out the memory issue. So I should add '--shm-size=10.24gb' to 'docker run'  as suggested in the message?I couldn't get any results saved in this run. Is the program designed to save results after each step is completed?

**Comment by SeppeDeWinter** [comment]
Hi.

Yes you could try that.
How much RAM do you have available on your system?

As to your question on wether it is designed to save after each step: The results are indeed stored in the scplus_obj, the try/excpect statement should ensure that the object is written to disk in case of an error. I guess in your case you ran out of walltime and python excited (in that case the object wont be written to disk)?

Best,

Seppe

**Comment by yupingz** [comment]
The server I used has over 700G available memory.

**Comment by SeppeDeWinter** [comment]
That should be enough in most cases! 

Are you running scenicplus using the docker image or did you install it using conda (or other package manager)?

**Comment by yupingz** [comment]
I use docker image. I am re-running run_scenicplus. I will update here how it goes.

**Comment by yupingz** [comment]
The hanging problem was solved by adding '--shm-size=10.24gb' to 'docker run' . 
But I ran into another error (below). I am guessing it is because some of my cluster have just a few cells. Any way to get around this? Thanks!

2022-09-23 17:01:36,548 SCENIC+_wrapper INFO     Formatting eGRNs
2022-09-23 17:15:25,969 SCENIC+_wrapper INFO     Converting eGRNs to signatures
2022-09-23 17:16:16,426 SCENIC+_wrapper INFO     Calculating eGRNs AUC
2022-09-23 17:16:16,426 SCENIC+_wrapper INFO     Calculating region ranking
2022-09-23 17:18:05,781 SCENIC+_wrapper INFO     Calculating eGRNs region based AUC
2022-09-23 17:18:38,602 SCENIC+_wrapper INFO     Calculating gene ranking
2022-09-23 17:18:45,396 SCENIC+_wrapper INFO     Calculating eGRNs gene based AUC
2022-09-23 17:19:09,834 SCENIC+_wrapper INFO     Calculating TF-eGRNs AUC correlation
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "<stdin>", line 2, in <module>
  File "/opt/venv/lib/python3.8/site-packages/scenicplus/wrappers/run_scenicplus.py", line 244, in run_scenicplus
    generate_pseudobulks(scplus_obj, 
  File "/opt/venv/lib/python3.8/site-packages/scenicplus/cistromes.py", line 223, in generate_pseudobulks
    sample_cells = sample(cells, nr_cells)
  File "/usr/local/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by SeppeDeWinter** [comment]
Hi @yupingz 

This error is indeed caused by the fact that some of your clusters only have very few cells (less than 5). You circumvent this step by setting `calculate_TF_eGRN_correlation` to `False` in `run_scenicplus`. 

We should add a check for this in the code.

Best,

Seppe

**Comment by SeppeDeWinter** [comment]
@biobai 

Please consider using the developmental branch.

see: https://github.com/aertslab/scenicplus/discussions/202 for more information.

Best,

Seppe
