### ISSUE TITLE
Step by step pipeline

### ISSUE THREAD

**Issue by SteveTur** [aertslab/scenicplus#366]
Hello,

We started our project using the step-by-step pipeline, which worked well on our datasets. However, we have not found back those tutorials since the update. 

Since we start all of our analysis with it, we would like to use it for the rest of our sample.

Do you plan to put them back?

Best,

Steven

**Comment by jesswhitts** [comment]
They're in the 'old' branch of this github repo, if you go to 'notebooks' you can download the old tutorials

**Comment by SteveTur** [comment]
Thank you so much! Is everything will work as before or do we need to update scenicplus?

**Comment by jesswhitts** [comment]
If you've got the previous version installed already, you should be able to follow the previous tutorials without updating. If you update to the new one you'll need to follow the new tutorials as the code is quite different.

**Comment by SeppeDeWinter** [comment]
I second what @jesswhitts is saying ;) 

Good luck with your analysis @SteveTur.

Best,

Seppe
