### ISSUE TITLE
some questions about the function score_eRegulons

### ISSUE THREAD

**Issue by aaaaaaaaaayong** [aertslab/scenicplus#369]
I successfully finished running the upstream process of the lasted version of the SCENICplus.But when I was doing downstream analysis, I ran into a problem. 

I want score eRegulon target genes and regions in cells using AUC algorithm by using score_eRegulons.This is the help description for this function:

score_eRegulons(
        eRegulons: pd.DataFrame,
        gex_mtx: pd.DataFrame,
        acc_mtx: pd.DataFrame,
        auc_threshold: float = 0.05,
        normalize: bool = False,
        n_cpu: int = 1
)

I don't understand what gex_mtx, acc_mtx refers to pd.DataFrame.

**Comment by SeppeDeWinter** [comment]
Hi @aaaaaaaaaayong 

This is how you should use the function:

```python

import mudata

mdata = mudata.read(<PATH_TO_MUDATA_OUTPUT>)

gene_region_AUC = score_eRegulons(
        eRegulons=mdata.uns["direct_e_regulon_metadata"],
        gex_mtx=mdata["scRNA"].to_df(),
        acc_mtx=mdata["scATAC"].to_df(),
        n_cpu=1)

```

I hope that helps?

All the best,

Seppe

**Comment by aaaaaaaaaayong** [comment]
Thanks for your help, this actually worked successfully

Thank you and wish you all the best 

ayong

**Comment by yojetsharma** [comment]
> Hi@SeppeDeWinter
> 
> Thanks for your help, this actually worked successfully.
> 
> Thank you and wish you all the best.
> 
> ayong

Hi, any idea how to generate the network plots as shown in the tutorial using the GSEA approach?
