### ISSUE TITLE
multi_ome_mode = False

### ISSUE THREAD

**Issue by orian116** [aertslab/scenicplus#372]
Hello,

Thank you for the updates o the package. I am running scenic+ using snakemake from sceniplus '1.0a1'. When I get to the "localrule prepare_GEX_ACC_multiome:" step I get the following error:
" No cells found which are present in both assays, check input and consider using `bc_transform_func`!"

 In my scATAC and scRNA datasets, I don't have the same barcodes but I have the same cell types annotated between the two. I know in the old version of scenic+ there was a way to create a pseudo multiome dataset simply by passing multi_ome_mode = False. Is there a way to do it automatically in this version? I see the bc_transform_func in the config.yaml but what function/argument do I pass to it?

**Comment by jesswhitts** [comment]
You want to edit the Snakemake config.yaml file, under 'params_data_preparation:' change 'is_multiome: False' and also set 'key_to_group_by:' to the name of your common cell type field

Best,
Jess
(not a part of scenic+ dev team btw, just passing...)

**Comment by orian116** [comment]
Thank you! That seems to work. However, my dataset is fairly large even after splitting by chromosome. Do you know the underlying functions that run this step so I could do it separately before running scenic+?

**Comment by SeppeDeWinter** [comment]
Thank you for answering @jesswhitts, that's indeed correct!

Good luck with the analysis @orian116 

Best,

Seppe
