### ISSUE TITLE
No enriched motifs found in Topics/DAR

### ISSUE THREAD

**Issue by XiaoKaixuan12333** [aertslab/scenicplus#377]
**Describe the bug**
hi, when i run the scenicplus according the tutorial using snakemake, i meet this question:
<img width="1156" alt="WechatIMG1262" src="https://github.com/aertslab/scenicplus/assets/68586901/bfedde79-845d-4222-b8fd-03a0051b03fd">

Before that, I have success run the customer-cisTarget-database according the tutorial. my species is macaque,  the out put is :
<img width="1273" alt="image" src="https://github.com/aertslab/scenicplus/assets/68586901/5e485445-13e4-4c55-8c15-2c7c5576bee3">

i don't know what happen.

Does anyone can help me?
thanks.

**Comment by SeppeDeWinter** [comment]
Hi @XiaoKaixuan12333 

Are you sure that you specified the correct cistarget database paths?
You should use the **score** database for DEM and the **ranking** database for cistarget.

All the best,

Seppe

**Comment by XiaoKaixuan12333** [comment]
hi, thanks for your reply, I have solve this problem. It was because I put it in the wrong place.
