### ISSUE TITLE
The tutorial for starting analysis with counting matrices cannot be opened

### ISSUE THREAD

**Issue by Linshiqi-Git** [aertslab/scenicplus#387]
Hi,
The page of https://pycistopic.readthedocs.io/en/latest/Toy_melanoma-RTD.html cannot be opened. The following information is displayed: You are browsing the documentation of pycistopic. The documentation page you are looking for was not found.

**Comment by SeppeDeWinter** [comment]
Hi @Linshiqi-Git 

You can still find the notebook at: https://github.com/aertslab/pycisTopic/blob/main/notebooks/Toy_melanoma-RTD.ipynb

Best,

Seppe
