### ISSUE TITLE
The required file cannot be found

### ISSUE THREAD

**Issue by LMBei3353** [aertslab/scenicplus#390]
Hello Dear author,
In SCENIC+ Tutorial: SCENIC+ step-by-step in the human cerebellum tutorial, there is a file "GRCh38_STAR_2.7.5_rna/genes.gtf" I do not know how to get, may I ask where to get this file.

**Comment by SeppeDeWinter** [comment]
Hi

A similar gtf file can be downloaded from: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/

Best,

Seppe
