### ISSUE TITLE
Can scRNA and scATAC paired data from multiple samples be used with Scenic+ ？

### ISSUE THREAD

**Issue by WhaleGe** [aertslab/scenicplus#40]
Hello, I have scRNA and scATAC data from multiple samples, can I use Scenic+? Because only one set of paired data is used in the PBMC tutorial.

**Comment by cbravo93** [comment]
Hi WhaleGe!

Yes it can. The pycistarget/SCENIC+ step will be exactly the same as for one sample, for pycisTopic you just need to provide your samples as entries in the fragments dictionary and indicate the sample of origin in cell_data (for example, here: https://pycistopic.readthedocs.io/en/latest/Cortex_pycisTopic.html ). For paired atac and rna (non multiome data, but runs in the same tissue), you can follow this tutorial: https://scenicplus.readthedocs.io/en/latest/mix_melanoma_cell_lines.html , which uses 2 samples.

Cheers!

C
