### ISSUE TITLE
build_grn hanging

### ISSUE THREAD

**Issue by valelorenzi9** [aertslab/scenicplus#41]
Hello, 

Thank you very much for developing this wonderful tool :) 

I have noticed that the function **build_grn** from scenicplus.grn_builder.gsea_approach in some cases seems to hang at the "Running GSEA..." step for a very long time (see screenshot). I am running it on a relatively small scenicplus object obtained by creating metacells from unpaired scRNA-seq and scATAC-seq data as per tutorial.

`SCENIC+ object with n_cells x n_genes = 228 x 21278 and n_cells x n_regions = 228 x 152615`

The notebook has now been running for over 10 hours with 20 cpu and it still has not finished. 

I did an identical analysis on another dataset of comparable size (roughly same number of metacells) and **build_grn** finished running in less than an hour, so I think something weird is going on here. Do you have any insights as why this might happen? Any suggestion would be greatly appreciated. 

**Version:**
 - Python: Python 3.8
 - SCENIC+: 0.1.dev437+ga57717f
 
<img width="775" alt="Screenshot 2022-09-27 at 06 52 29" src="https://user-images.githubusercontent.com/56558975/192444449-3a7eb6d8-aae7-4553-b40b-9ad2d7dccfb9.png">

**Comment by cbravo93** [comment]
Hi @valelorenzi9 !

Could you run it without silencing errors and post the output of that? We need more information.

Cheers!

C

**Comment by valelorenzi9** [comment]
Hi @cbravo93, thank you very much for looking into this! 
Attached is the output without silencing errors. 

Thanks! 

<img width="855" alt="Screenshot 2022-09-27 at 09 04 14" src="https://user-images.githubusercontent.com/56558975/192470017-191cd37d-1b9a-4158-b84d-c5577d935028.png">

**Comment by cbravo93** [comment]
Can you specify tempDir to a path were you have more space instead of default?

**Comment by valelorenzi9** [comment]
I did but it still gives the same error... 

I saw that somebody suggested decreasing the number of CPU when this error message pops us (https://github.com/ray-project/ray/issues/25012), so I tried that but now it is just hanging at "**Running GSEA..**." for a few hours (without throwing the `Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"`)

**Comment by cbravo93** [comment]
Are you in a Docker container?

**Comment by valelorenzi9** [comment]
No, I am running it in a notebook on a virtual machine with 400 GiB RAM

**Comment by cbravo93** [comment]
Lowering the cores to 5 helps?

**Comment by cbravo93** [comment]
Is that the whole error output? Do you get 'Spilled...' messages? It sounds similar to https://github.com/aertslab/scenicplus/issues/36 but not exactly the same based on the error above

**Comment by valelorenzi9** [comment]
Yes that was the whole error output, no memory spilling messages. I tried lowering to 5 cores but while the error message disappears it still just hangs at the "Running GSEA..." step (has been running for three hours now). I don't understand how I got it to work smoothly on another dataset of comparable size and it is not working on this.

**Comment by valelorenzi9** [comment]
Can I also ask where you got the **genes.gtf** file that you are using for plotting the multiome data? 

Thanks!

**Comment by valelorenzi9** [comment]
Hi @cbravo93! Just a heads up that I managed to fix the issue by cleaning the tmp_dir before running the _build_grn_ command. Thanks!

**Comment by cbravo93** [comment]
Hi Valentina!

Thank you very much for reporting the solution, this can be useful for users in the same situation :).

Cheers!

C
