### ISSUE TITLE
ModuleNotFoundError: No module named 'scenicplus.dimensionality_reduction'

### ISSUE THREAD

**Issue by dsecilmis** [aertslab/scenicplus#417]
Trying to run plot_perturbation_effect_in_embedding(...) but getting the following ModuleNotFoundError: No module named 'scenicplus.dimensionality_reduction'.

Indeed I cannot find the dimensionality_reduction module in the repo. I also checked if the plot_metadata_given_ax function has been moved somewhere else but couldn't find it. Any idea where it might be?

Thanks!

**Comment by SeppeDeWinter** [comment]
Hi @dsecilmis 

This code has now been updated: https://scenicplus.readthedocs.io/en/latest/Perturbation_simulation.html#Tutorial:-Perturbation-simulation

All the best,

Seppe

**Comment by GayaniSene** [comment]
Hi Seppe, This issue still coming up even with the newest update for the package. "ModuleNotFoundError: No module named 'scenicplus.dimensionality_reduction'"

Could you please let us know how to fix this? 

Thanks!
