### ISSUE TITLE
issue with RAY package while running a jupyter notebook

### ISSUE THREAD

**Issue by sid5427** [aertslab/scenicplus#42]
Hi Authors,

Thank you for your work in developing this package.

I have an issue while trying to run the 10x multiome pbmc tutorial.

Working with - 
```
python 3.8 - version 3.8.13
scenicplus.__version__
'0.1.dev447+gd4fd733'
``` 

I downloaded the ipynb file for the tutorial and executing it independently on our server. We have an LSF based schedule (bsub commands) and I using nbconvert to run the script.

This is the command I am running -
```
 bsub -W 5:00 -M 128000 -n 1 -o jup_try.out -e jup_try.err jupyter nbconvert \
--to notebook \
--allow-errors=True \
--ExecutePreprocessor.timeout=-1 \
--execute pbmc_multiome_tutorial.ipynb
```
 
Essentially the script gets stuck at building the run_cgs_models() step - (code block 39 in the notebook below). 

I tried both multicore/processor execution and single core/processor. I changed the "n_cpu" parameter to 10, 5, and 1. Concurrently I also changed the "-n" flag in the above bsub command to match the number of n_cpu. i.e. if n_cpu = 5, then bsub -n 5 and so forth. It seems the RAY package throws a timeout error.

Here is the output jupyter notebook with the results of each step running in "single processor/cpu mode"
- [notebook_out](https://drive.google.com/file/d/17jDe-3fhWGp7JpHuroOjRsAjKE0kzohr/view?usp=sharing)

Any help troubleshooting this would be appreciated!

**Comment by SeppeDeWinter** [comment]
Hi

I did not yet try running the notebook using nbconvert on our system. I don't suspect this to be the problem but I will give it a try to make sure that is working in our hands.

I'm not too familiar with LSF based schedulers and I also don't have access to a system that uses this kind of scheduler so I'm afraid I can not help troubleshooting there.

A common issue with ray is the `_temp_dir` not being specified correctly. I see that you changed the path in the notebook. Can you make sure this folder exists and you can access it from the place where the notebook is executed?

I would suggest to make another notebook just to test ray, containing the following snippet:

```python
import ray
import os
tmp_dir = 'temp_files'
ray.init(num_cpus=5,  _temp_dir = os.path.join(tmp_dir + 'ray_spill')

@ray.remote
def f(x):
    return x * x

futures = [f.remote(i) for i in range(4)]
print(ray.get(futures)) 
```
(example from: https://docs.ray.io/en/latest/ray-overview/index.html)

This should print 
```python
>> [0, 1, 4, 9]
```

Hope this helps,
Best.

Seppe

**Comment by sid5427** [comment]
Hi Seppe,

Thank you for the help with this - I'll give your suggestion a try and report back.

--
Regards,
Sid

**Comment by sid5427** [comment]
Hi Seppe,

I am still troubleshooting this issue - for now I am running on an independent server and it seems to work fine on that. I'll move to working on our cluster after this round. Thanks.

**Comment by SeppeDeWinter** [comment]
Hi Sid

Glad to hear that things are starting to work!

Let me know if you encounter more issues.

Good luck.


Best,
Seppe
