### ISSUE TITLE
SCENIC+ prepare_menr error: TypeError unbound method set.union() needs an argument

### ISSUE THREAD

**Issue by jklvrt** [aertslab/scenicplus#442]
Hi, 

Managed to reach the SCENIC+ steps, but while running through CLI reached this error at the prepare_menr step (images attached of log file and CL output). Any ideas/help would be greatly appreciated 

<img width="1440" alt="Screenshot 2024-08-04 at 13 28 54" src="https://github.com/user-attachments/assets/a656213c-b968-43a2-bec0-9d21e8d5c492">
<img width="1440" alt="Screenshot 2024-08-04 at 13 28 21" src="https://github.com/user-attachments/assets/fd7430c9-d87b-4fb7-88ec-e6ff776872c0">

**Comment by jklvrt** [comment]
was a mistake in input setup.... :)

**Comment by irepansalvador** [comment]
Hi @jklvrt 
could you please elaborate on the input setup mistake you found?
I am getting exactly the same prepare_menr error but I haven't yet figure out what could be happening.
Any help would be appreciated.
Irepan

**Comment by jklvrt** [comment]
My input file setup was wrong, specifically the 'path_to_motif_annotations' variable was wrongly set to just the tf list file, instead of the actual motif annotation table : [motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl](https://resources.aertslab.org/cistarget/motif2tf/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl),
Hope this is the reason behind your error

**Comment by irepansalvador** [comment]
Thanks for your prompt response, this doesnt seem to be the reason behind my error as in my case my input file is pointing at the motif annotation table. I suppose my error is related to the fact I am using scenicplus with a different species from the default (I am using pig as species), as I managed to run scenicplus successfully with mouse.
I will create a new issue describing my error. thanks again!

**Comment by Yiming-Huang-neuron** [comment]
Hi, I met the same mistake. I fail run on mouse data, but succeed on human data. I used the matching tf list file which I have checked as input. @irepansalvador  did you fix your mistakes?

**Comment by irepansalvador** [comment]
Hi @Yiming-Huang-neuron , I managed to run the whole pipeline. In my case I needed to create a custom `genome_annotation` file and also a `path_to_motif_annotations` file, as I was dealing with another species. I didn't have this error when analysing mouse data though.

**Comment by Yiming-Huang-neuron** [comment]
@irepansalvador Hi, thanks for your reply, but I still have not fixed this mistake even after a week has passed. I wonder if it has to do with the threshold I set.

Best

Yiming

**Comment by Melody-cell** [comment]
Hi, @jklvrt , i had the same error as you.
Do you know how to solve it?
![image](https://github.com/user-attachments/assets/8d3c8565-7319-4377-a520-88c2ad01cae2)

**Comment by capuddddd** [comment]
> Hi, [@jklvrt](https://github.com/jklvrt) , i had the same error as you. Do you know how to solve it? ![image](https://github.com/user-attachments/assets/8d3c8565-7319-4377-a520-88c2ad01cae2)

hi，@Melody-cell  did you solve this problem, i have this problem as well, and i don't know which casues this?
