### ISSUE TITLE
Input annotated 10x Multiome Seurat object into SCENIC+

### ISSUE THREAD

**Issue by strawberry098** [aertslab/scenicplus#452]
Is it possible to input clustered and annotated 10x Multiome Seurat object into SCENIC+?

Then it is not necessary to cluster the cells according to: 
https://github.com/aertslab/pycisTopic/blob/old/notebooks/Toy_melanoma-RTD.ipynb 

But how can I retrieve the region sets to run SCENIC+?

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

Please don't open duplicate issues: https://github.com/aertslab/scenicplus/issues/451.

All the best,

Seppe
