### ISSUE TITLE
how much resource needed? Multiome datasets with 270k cells

### ISSUE THREAD

**Issue by JinKyu-Cheong** [aertslab/scenicplus#453]
Hi

Thanks for the great tools for multiome dataset. we have some questions about the running this tool.

1. We have multiome data with 270K cells. we would like to run Scenic+ on ours. Could you provide some information of how much computational resources (core, memory, time) we should request from server? 
2. Have you applied metacell approach before? if so could you share your experience?
3. The FAQ mentioned that we could start from available ArchR data, but the link to the specific tutorial is not working. Could you fix that please?

Thank you.

**Comment by SeppeDeWinter** [comment]
Hi

1. I would request ~250 gb ram, ~20 cores and ~12 hours.
2. I have not used metacells before.
3. The requested tutorial can be found here: https://github.com/aertslab/pycisTopic/blob/old/notebooks/Toy_melanoma-RTD.ipynb

I hope I was able to resolve your issue using this.

All the best,

Seppe
