### ISSUE TITLE
Re-running old SCENIC+ pipeline in the new version without snakemake

### ISSUE THREAD

**Issue by skoturan** [aertslab/scenicplus#457]
Hi,

I'm struggling to reproduce my results done by the old SCENIC+ as my environment seems to have stopped working. Is there a way to look at the old files in the new version of SCENIC+?

Alternatively, do you have a detailed tutorial for using the new SCENIC+ to re-run all the steps in the pipeline from scATAC preprocessing with cisTopic, cisTarget, etc.?
Hope you can help
Thanks

**Comment by SeppeDeWinter** [comment]
Hi @skoturan 

The tutorial can be found here: https://scenicplus.readthedocs.io/en/latest/tutorials.html

All the best,

Seppe

**Comment by skoturan** [comment]
Thank you for the new tutorial-  I will try this!
