### ISSUE TITLE
Error in rule eGRN_extended - ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by maithermbarros** [aertslab/scenicplus#460]
**Describe the bug**
When running scenicplus most of the pipeline works but when I get to eGRN_extended it fails. I already tried creating a new conda enviroment, reinstalling all packages, running snakemake in a brand new empty folder, but nothing works.

**To Reproduce**
I prepared all files and ran snakemake within my conda environment 

```
conda env remove --name scenicplus_311_integrated
conda create --name scenicplus_3-11-8 python=3.11.8 -y
conda activate scenicplus_3-11-8

git clone https://github.com/aertslab/scenicplus
cd scenicplus
pip install .
scenicplus init_snakemake --out_dir scplus_pipeline_3rdtry
nano config.yaml # configure ymal file
snakemake --cores 10
```

**Error output**
Here's the full snakemake error log, but basically I get an ValueError saying "No objects to concatenate".
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job stats:
job                            count
---------------------------  -------
AUCell_direct                      1
AUCell_extended                    1
all                                1
download_genome_annotations        1
eGRN_direct                        1
eGRN_extended                      1
get_search_space                   1
motif_enrichment_cistarget         1
motif_enrichment_dem               1
prepare_GEX_ACC_multiome           1
prepare_menr                       1
region_to_gene                     1
scplus_mudata                      1
tf_to_gene                         1
total                             14

Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 15:01:12 2024]
localrule motif_enrichment_cistarget:
    input: /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/output/region_sets, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl
    output: ctx_results.hdf5, ctx_results.html
    jobid: 9
    reason: Missing output files: ctx_results.hdf5
    threads: 10
    resources: tmpdir=/tmp

[Tue Sep  3 15:41:24 2024]
Finished job 9.
1 of 14 steps (7%) done
Select jobs to execute...
Execute 2 jobs...

[Tue Sep  3 15:41:24 2024]
localrule download_genome_annotations:
    output: genome_annotation.tsv, chromsizes.tsv
    jobid: 8
    reason: Missing output files: genome_annotation.tsv, chromsizes.tsv
    resources: tmpdir=/tmp


[Tue Sep  3 15:41:24 2024]
localrule prepare_GEX_ACC_multiome:
    input: /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/output/cistopic_mergedobj_model.pkl, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/adata_diet_matchingids.h5ad
    output: ACC_GEX.h5mu
    jobid: 2
    reason: Missing output files: ACC_GEX.h5mu
    resources: tmpdir=/tmp

[Tue Sep  3 15:42:35 2024]
Finished job 8.
2 of 14 steps (14%) done
Select jobs to execute...
[Tue Sep  3 16:02:21 2024]
Finished job 2.
3 of 14 steps (21%) done
Execute 1 jobs...

[Tue Sep  3 16:02:21 2024]
localrule get_search_space:
    input: ACC_GEX.h5mu, genome_annotation.tsv, chromsizes.tsv
    output: search_space.tsv
    jobid: 11
    reason: Missing output files: search_space.tsv; Input files updated by another job: ACC_GEX.h5mu, genome_annotation.tsv, chromsizes.tsv
    resources: tmpdir=/tmp

[Tue Sep  3 16:08:28 2024]
Finished job 11.
4 of 14 steps (29%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 16:08:28 2024]
localrule region_to_gene:
    input: ACC_GEX.h5mu, search_space.tsv
    output: region_to_gene_adj.tsv
    jobid: 10
    reason: Missing output files: region_to_gene_adj.tsv; Input files updated by another job: ACC_GEX.h5mu, search_space.tsv
    threads: 10
    resources: tmpdir=/tmp

[Tue Sep  3 16:10:40 2024]
Finished job 10.
5 of 14 steps (36%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 16:10:40 2024]
localrule motif_enrichment_dem:
    input: /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/output/region_sets, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.scores.feather, genome_annotation.tsv, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl
    output: dem_results.hdf5, dem_results.html
    jobid: 7
    reason: Missing output files: dem_results.hdf5; Input files updated by another job: genome_annotation.tsv
    threads: 10
    resources: tmpdir=/tmp

[Tue Sep  3 16:51:57 2024]
Finished job 7.
6 of 14 steps (43%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 16:51:57 2024]
localrule prepare_menr:
    input: dem_results.hdf5, ctx_results.hdf5, ACC_GEX.h5mu
    output: tf_names.txt, cistromes_direct.h5ad, cistromes_extended.h5ad
    jobid: 6
    reason: Missing output files: cistromes_extended.h5ad, cistromes_direct.h5ad, tf_names.txt; Input files updated by another job: dem_results.hdf5, ACC_GEX.h5mu, ctx_results.hdf5
    resources: tmpdir=/tmp

[Tue Sep  3 16:59:32 2024]
Finished job 6.
7 of 14 steps (50%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 16:59:32 2024]
localrule tf_to_gene:
    input: ACC_GEX.h5mu, tf_names.txt
    output: tf_to_gene_adj.tsv
    jobid: 5
    reason: Missing output files: tf_to_gene_adj.tsv; Input files updated by another job: ACC_GEX.h5mu, tf_names.txt
    threads: 10
    resources: tmpdir=/tmp

[Tue Sep  3 20:29:46 2024]
Finished job 5.
8 of 14 steps (57%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Sep  3 20:29:46 2024]
localrule eGRN_extended:
    input: tf_to_gene_adj.tsv, region_to_gene_adj.tsv, cistromes_extended.h5ad, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather
    output: eRegulons_extended.tsv
    jobid: 13
    reason: Missing output files: eRegulons_extended.tsv; Input files updated by another job: cistromes_extended.h5ad, region_to_gene_adj.tsv, tf_to_gene_adj.tsv
    threads: 10
    resources: tmpdir=/tmp

[Tue Sep  3 20:30:57 2024]
Error in rule eGRN_extended:
    jobid: 13
    input: tf_to_gene_adj.tsv, region_to_gene_adj.tsv, cistromes_extended.h5ad, /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather
    output: eRegulons_extended.tsv
    shell:
        
        scenicplus grn_inference eGRN             --is_extended             --TF_to_gene_adj_fname tf_to_gene_adj.tsv            --region_to_gene_adj_fname region_to_gene_adj.tsv             --cistromes_fname cistromes_extended.h5ad             --ranking_db_fname /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather             --eRegulon_out_fname eRegulons_extended.tsv             --temp_dir /mnt/scratch/maithe/SCENICplus_temp_P1-B1-B2P1-B2P3R2/scplus_pipeline             --order_regions_to_genes_by importance             --order_TFs_to_genes_by importance             --gsea_n_perm 1000             --quantiles 0.85 0.90 0.95             --top_n_regionTogenes_per_gene 5 10 15             --top_n_regionTogenes_per_region              --min_regions_per_gene 0             --rho_threshold 0.05             --min_target_genes 10             --n_cpu 10
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-03T150112.662151.snakemake.log
WorkflowError:
At least one job did not complete successfully.

```

**Expected behavior**
I checked the input files and they are all in the correct folder, correctly spelled and seem to be all fine.

**Version (please complete the following information):**
 - Python: 3.11.8 miniconda environemnt
 - SCENIC+: 0.1
 - Pandas: 1.5.0
 - Dask: 2024.2.1

**Additional context**
I tried running the code outside of snakemake, but it did not work either:
`(scenicplus_3-11-8) maithe@kno01:/mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICplus_P1-B1-B2P1-B2P3R2/scplus_pipeline_3rdtry_3118/Sn                                                                                                                                                                akemake$ scenicplus grn_inference eGRN --is_extended --TF_to_gene_adj_fname tf_to_gene_adj.tsv            --region_to_gene_adj_fname region_to_gene_adj.tsv                                                                                                                                                                             --cistromes_fname cistromes_extended.h5ad             --ranking_db_fname /mnt/data/maithe/Gastric-Origins-Project/Gastric_Origin_Multiome/SCENICpl                                                                                                                                                                us_P1-B1-B2P1-B2P3R2/input/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather             --eRegulon_out_fname eRegulons_extended.tsv             --tem                                                                                                                                                                p_dir /mnt/scratch/maithe/SCENICplus_temp_P1-B1-B2P1-B2P3R2/scplus_pipeline             --order_regions_to_genes_by importance             --order_TFs_to_gen                                                                                                                                                                es_by importance             --gsea_n_perm 1000             --quantiles 0.85 0.90 0.95             --top_n_regionTogenes_per_gene 5 10 15             --top_n                                                                                                                                                                _regionTogenes_per_region              --min_regions_per_gene 0             --rho_threshold 0.05             --min_target_genes 10             --n_cpu 10
2024-09-04 12:13:52,313 SCENIC+      INFO     Loading TF to gene adjacencies.
2024-09-04 12:13:53,430 SCENIC+      INFO     Loading region to gene adjacencies.
2024-09-04 12:13:53,433 SCENIC+      INFO     Loading cistromes.
2024-09-04 12:13:53,605 GSEA         INFO     Thresholding region to gene relationships
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:36<00:00,  2.61s/it]
2024-09-04 12:14:30,349 GSEA         INFO     Subsetting TF2G adjacencies for TF with motif.
2024-09-04 12:14:30,476 GSEA         INFO     Running GSEA...
2024-09-04 12:14:30,476 GSEA         INFO     Generating rankings...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 373/373 [00:01<00:00, 250.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 [00:00<00:00, 1975.24it/s]
Running for Positive TF to gene:   0%|                                                                                              | 0/3865 [00:00<?, ?it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:   1%|▌                                                                                    | 25/3865 [00:05<13:50,  4.62it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped whil                                                                                                                                                                e some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:   3%|██▎                                                                                 | 108/3865 [00:13<05:05, 12.30it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:   5%|███▉                                                                                | 182/3865 [00:13<01:54, 32.16it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:   9%|███████▋                                                                            | 353/3865 [00:14<00:40, 85.97it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:  15%|████████████▎                                                                      | 571/3865 [00:15<00:22, 144.34it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:  20%|████████████████▌                                                                  | 774/3865 [00:16<00:16, 190.31it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:  23%|██████████████████▋                                                                | 872/3865 [00:17<00:15, 196.12it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
Running for Positive TF to gene:  25%|█████████████████████                                                              | 981/3865 [00:17<00:12, 236.39it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:  31%|█████████████████████████▌                                                        | 1203/3865 [00:18<00:09, 267.47it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene:  40%|████████████████████████████████▉                                                 | 1551/3865 [00:18<00:06, 347.74it/s]                                                                                                                                                                /home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:71: RuntimeWarning: divide by zero encountered in divide
  norm_tag =  1.0/sum_correl_tag
/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/gseapy/algorithm.py:74: RuntimeWarning: invalid value encountered in multiply
  RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)
Running for Positive TF to gene: 100%|██████████████████████████████████████████████████████████████████████████████████| 3865/3865 [00:25<00:00, 154.38it/s]
Running for Negative TF to gene: 100%|████████████████████████████████████████████████████████████████████████████████| 3865/3865 [00:00<00:00, 12600.68it/s]
2024-09-04 12:14:58,996 GSEA         INFO     Subsetting on adjusted pvalue: 1, minimal NES: 0 and minimal leading edge genes 10
2024-09-04 12:14:58,997 GSEA         INFO     Merging eRegulons
2024-09-04 12:14:59,039 SCENIC+      INFO     Formatting eGRN as table.
Traceback (most recent call last):
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/bin/scenicplus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 1137, in main
    args.func(args)
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 861, in eGRN
    infer_grn(
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/scenicplus/cli/commands.py", line 912, in infer_grn
    eRegulon_metadata = _format_egrns(
                        ^^^^^^^^^^^^^^
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/scenicplus/cli/commands.py", line 790, in _format_egrns
    eRegulon_metadata = pd.concat(eRegulons_formatted)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 369, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/maithe/miniconda3/envs/scenicplus_3-11-8/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 426, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
`

Any help would be greatly appreciated. Thanks a lot!

**Comment by maithermbarros** [comment]
I was inspecting my files again and there seems to be a problem with my "search_space" and "region_to_gene_adj" files. 

"search_space" only has a few genes in the list, which seems odd:
![image](https://github.com/user-attachments/assets/d0031a50-58de-44d9-bc1a-29fea5a839d7)


Consequently I have only a few unique targets and a total of 784 rows in region to gene adj. Here's how part of my region to gene adj file looks like:
![image](https://github.com/user-attachments/assets/7cb2a3b3-9928-4468-9759-7c29b6038ebe)


I wonder what could have gone wrong when creating these files. I know that the files ACC_GEX.h5mu, genome_annotation.tsv and chromsizes.tsv are used to create search_space.tsv. These look ok to me, but maybe I am missing something?

![image](https://github.com/user-attachments/assets/de925e6d-2666-4bd5-9bfc-1cc8e6d89739)
![image](https://github.com/user-attachments/assets/9f504648-5562-4874-8441-88dda7c28b83)
![image](https://github.com/user-attachments/assets/8768add0-ba0b-484b-93ee-655aecd8c701)







Is there a guide somewhere that shows us what snakemake does step by step so I can try and traceback what has been done up to where I get an error? Thanks

**Comment by maithermbarros** [comment]
I rerun the pipeline and got it to work now. There was something wrong with the way genes were annotated in the genome_annotation file that gets downloaded during the snakemake pipeline.

**Comment by maithermbarros** [comment]
I rerun the pipeline and got it to work now. There was something wrong with the way genes were annotated in the genome_annotation file that gets downloaded during the snakemake pipeline.

**Comment by JianiC** [comment]
> I rerun the pipeline and got it to work now. There was something wrong with the way genes were annotated in the genome_annotation file that gets downloaded during the snakemake pipeline.

@maithermbarros Hi, I am having the exact same problem, the search_space.tsv has the same genes as you list before, would you mind sharing how to work through it and any insights for causing this issue?

<img width="86" alt="Image" src="https://github.com/user-attachments/assets/dc440b05-2f91-4fd5-ab99-c9be1fd903f4" />
