### ISSUE TITLE
An error during calculate_TFs_to_genes_relationships()

### ISSUE THREAD

**Issue by bavanesyan** [aertslab/scenicplus#47]
**Describe the bug**
In the SCENIC+ object, my expression matrix was stored in a form of a sparse matrix by default. 
![image](https://user-images.githubusercontent.com/48180833/194575303-e9812fe2-5d4b-41f8-9126-7c6839234289.png)

During `calculate_TFs_to_genes_relationships()` step expression matrix in a form of a pandas dataframe is required (_TF_to_gene.py module, line 333_). The function tries to call it with:
```
ex_matrix = pd.DataFrame(
        scplus_obj.X_EXP, index=scplus_obj.cell_names, columns=scplus_obj.gene_names)
```
However, this approach is not suitable for sparse matrixes and results in error: `ValueError: Shape of passed values is (9307, 1), indices imply (9307, 27477)`

I bypassed this error by using the default method `.to_df(layer="EXP")`:
`ex_matrix = scplus_obj.to_df(layer="EXP")`

It might be a good idea to fix this dangerous spot.

**Comment by SeppeDeWinter** [comment]
Hi @bavanesyan 

Thank you for the bug report, you are correct!

This is the reason for the following line in the tutorial:
https://scenicplus.readthedocs.io/en/latest/pbmc_multiome_tutorial.html#inferring-enhancer-driven-Gene-Regulatory-Networks-(eGRNs)-using-SCENIC+

```python

from scenicplus.scenicplus_class import create_SCENICPLUS_object
import numpy as np
scplus_obj = create_SCENICPLUS_object(
    GEX_anndata = adata.raw.to_adata(),
    cisTopic_obj = cistopic_obj,
    menr = menr,
    bc_transform_func = lambda x: f'{x}-10x_pbmc' #function to convert scATAC-seq barcodes to scRNA-seq ones
)
scplus_obj.X_EXP = np.array(scplus_obj.X_EXP.todense()) #<------ THIS ONE
scplus_obj

```

This is something that will be changed in the next release, thanks for pointing it out.

Best,

Seppe
