### ISSUE TITLE
Dataset for 10x pbmc multiome

### ISSUE THREAD

**Issue by tu4n-p** [aertslab/scenicplus#49]
Hi there I was trying to test the 10x pbmc multiome tutorial but got trouble with the datasets below:
rankings_db = os.path.join(db_fpath, 'cluster_SCREEN.regions_vs_motifs.rankings.v2.feather')
scores_db =  os.path.join(db_fpath, 'cluster_SCREEN.regions_vs_motifs.scores.v2.feather')
I found similar ones but not the exact same "hg38_screen_v10_clust.regions_vs_motifs.rankings.feather" and "hg38_screen_v10_clust.regions_vs_motifs.scores.feather".  The files seem a bit too big so I'm wondering if there are smaller size files that I could try. Thank you,

**Comment by SeppeDeWinter** [comment]
Hi

Yes that should be the correct file.
Unfortunately these files are indeed quite big by nature, we don't have any smaller files to try.

Best,

Seppe
