### ISSUE TITLE
Issue with scenicplus.wrappers

### ISSUE THREAD

**Issue by idalarsson** [aertslab/scenicplus#50]
Hi,

I've been working my way through the pbmc tutorial but have encountered a problem in the section "Motif enrichment analysis using pycistarget". When I try to import the run_pycistarget() command using 
`from scenicplus.wrappers.run_pycistarget import run_pycistarget` 
I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scenicplus.wrappers'
```

From what I can see, the scenicplus package is imported without giving any errors. This is the session info:

```
>>> session_info.show(html=False) 

PIL                 9.2.0
adjustText          NA
gensim              4.2.0
harmonypy           NA
igraph              0.10.1
lda                 2.0.0
leidenalg           0.9.0
matplotlib          3.6.0
numpy               1.22.0
pandas              1.5.0
pybiomart           0.2.0
pycisTopic          1.0.2.dev9+gaf3977c
pycistarget         1.0.2.dev9+g0ed8289
pyranges            0.0.117
pyscenic            0.12.0+7.gc120979
ray                 2.0.0
requests            2.28.1
scanpy              1.9.1
scenicplus          NA
scipy               1.9.1
seaborn             0.12.0
session_info        1.0.0
sklearn             1.0.2
tmtoolkit           0.11.2
umap                0.5.3

IPython             8.0.1
jupyter_client      7.1.2
jupyter_core        4.9.1
notebook            6.4.8

Python 3.9.1 (default, Dec 11 2020, 06:28:49) [Clang 10.0.0 ]
macOS-10.16-x86_64-i386-64bit

Session information updated at 2022-10-14 08:00
>>> 

```
Thank you in advance!

**Comment by SeppeDeWinter** [comment]
Hi @idalarsson 

Are you sure you install scenicplus correctly?

```bash

conda create --name scenicplus python=3.8
conda activate scenicplus
git clone https://github.com/aertslab/scenicplus
cd scenicplus
pip install -e .

```

I just did a fresh install and all is working fine on my side

```bash

conda create --name scenicplus_debug python=3.8
conda activate scenicplus_debug
git clone https://github.com/aertslab/scenicplus
cd scenicplus
pip install -e .

```

```python

import scenicplus
scenicplus.__version__
>>> '0.1.dev447+gd4fd733'

```

```python

from scenicplus.wrappers.run_pycistarget import run_pycistarget

```

Could you try reinstalling the package?

Best,

Seppe

**Comment by idalarsson** [comment]
Hi!

I redid the install and now it works. I missed the last time that an error occurred, I write it here and how I solved it in case someones else has the same problem. When installing scenicplus, the package fa2 (forceatlas2) cast an error. It was solved by first installing it from source and then installing scenic+.

Thank you for the input!

**Comment by SeppeDeWinter** [comment]
Hi 

I'm glad it is working now. I did not have an issue with fa2, but I'm happy you could solve it quite easily. 
Thanks for sharing.

Best

S
