### ISSUE TITLE
Unpaired examples

### ISSUE THREAD

**Issue by Melody-cell** [aertslab/scenicplus#503]
@SeppeDeWinter Hi,
I recently found that the tutorial using unpaired scATAC-seq and scRNA-seq in melanoma cell lines: https://scenicplus.readthedocs.io/en/latest/mix_melanoma_cell_lines.html does not exist.
Do you know how to find it ?

Many thanks for your consideration

**Comment by SeppeDeWinter** [comment]
Hi @Melody-cell 

See my comment at: https://github.com/aertslab/scenicplus/issues/75

Best.

Seppe
