### ISSUE TITLE
Sure! Here’s the translation of your request into English:  ---  The **scenicplus** library is not installing. I've been trying for a month, and it doesn't install even in a Conda virtual environment. It gives the following error. Please help me to install the library.  ---   If you provide the specific error message you're encountering, I can assist you further in troubleshooting the installation of the **scenicplus** library.

### ISSUE THREAD

**Issue by sajadfatahi** [aertslab/scenicplus#508]
**Describe the bug**

**To Reproduce**
Commands relevant to reproduce the error.

**Error output**
Paste the entire output of the command, including log information prior to the error.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python: [e.g. Python 3.7.4]
 - SCENIC+: [e.g. 0.1.dev40+g4ff5053.d20210520]
 - If a bug is related to another module [e.g. matplotlib 3.3.9]

**Additional context**

**Comment by SeppeDeWinter** [comment]
Hi @sajadfatahi 

Please don't open duplicate issues.
https://github.com/aertslab/scenicplus/issues/507

Best,

Seppe
