### ISSUE TITLE
db_fpath and motif_annot_fpath files.

### ISSUE THREAD

**Issue by sid5427** [aertslab/scenicplus#51]
Hi,

Could you please give a link to download the files in bold below

rankings_db = os.path.join(db_fpath, '**cluster_SCREEN.regions_vs_motifs.rankings.v2.feather**')
scores_db =  os.path.join(db_fpath, '**cluster_SCREEN.regions_vs_motifs.scores.v2.feather**')
motif_annotation = os.path.join(motif_annot_fpath, '**motifs-v10-nr.hgnc-m0.00001-o0.0.tbl**')

I am mainly using the 10x multiome tutorial to troubleshoot and get scenic+ to run on our cluster, I also changed my paths as below, so I assume these files have to be downloaded or generated

```
db_fpath = "/staging/leuven/stg_00002/lcb/icistarget/data/make_rankings/v10_clust/CTX_hg38"
motif_annot_fpath = "/staging/leuven/stg_00002/lcb/cbravo/cluster_motif_collection_V10_no_desso_no_factorbook/snapshots"

was changed to 

db_fpath = "db_fpath_files/"
motif_annot_fpath = "motif_annot_fpath_files/ "
```

I think it would be a good idea to include the links for such files in the jupyter notebook - useful if someone is trying to get the tool to run and then work on generating intermediate files.

Thanks for the help!

**Comment by SeppeDeWinter** [comment]
Hi Sid

These files are available on: https://resources.aertslab.org/cistarget/

Please let me know if you have trouble finding the correct files.

Best

Seppe

**Comment by bitcometz** [comment]
@SeppeDeWinter , thanks for this great tool.

there are so many files under : https://resources.aertslab.org/cistarget/

I am new here, could you please tell me which folders contain the above files ?

Thanks !!!

**Comment by SeppeDeWinter** [comment]
Hi @bitcometz 

For human, see: https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/
For mouse, see: https://resources.aertslab.org/cistarget/databases/mus_musculus/mm10/screen/mc_v10_clust/region_based/

I hope this helps.

Best,

Seppe
