### ISSUE TITLE
create_cistarget_motif_databases

### ISSUE THREAD

**Issue by gilgolan73** [aertslab/scenicplus#517]
**Describe the bug**
Hi,
I try to create a custom cistarget motif database according to the tutorial:
https://scenicplus.readthedocs.io/en/latest/human_cerebellum_ctx_db.html
However, when I ran the create_cistarget_motif_databases I get an error that the scoring was not done for any of the motifs (see error message below). 
Please help. 

**To Reproduce**
"${SCRIPT_DIR}/create_cistarget_motif_databases.py"     -f ${FASTA_FILE}     -M ${CBDIR}     -m ${MOTIF_LIST}     -o ${OUT_DIR}/${DATABASE_PREFIX}     --bgpadding 1000     -t 20     -c "/home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/cbust" 

**Error output**
For any of the motifs, I get this message: 
Error: Non-zero exit status for: '/home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/cbust -f 4 -c 0.0 -r 10000 -b 1000 -t 1 /home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/aertslab_motif_colleciton/v10nr_clust_public/singletons/transfac_public__M00159.cb /home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/mm10.p3_pituitary_multiomic.with_1kb_bg_padding.fa'
Error: Non-zero exit status for: '/home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/cbust -f 4 -c 0.0 -r 10000 -b 1000 -t 1 /home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/aertslab_motif_colleciton/v10nr_clust_public/singletons/yetfasco__YDR174W_2249.cb /home/gilgolan/bioinfo_analysis/scenicplus_multiomic/cistarget/mm10.p3_pituitary_multiomic.with_1kb_bg_padding.fa'

Scoring 10249 motifs with Cluster-Buster took: 305.962677 seconds

Error: None of 10249 motifs were scored successfully.

**Expected behavior**
Motifs will be scored, a cistarget database will be created. 

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python: 3.11.10
 - SCENIC+:1.0a1
 - If a bug is related to another module [e.g. matplotlib 3.3.9]

**Additional context**

**Comment by SeppeDeWinter** [comment]
Hi @gilgolan73 

Can you please post your issue on: https://github.com/aertslab/create_cisTarget_databases

All the best,

Seppe
