### ISSUE TITLE
Issues with find_diff_features function in workflow

### ISSUE THREAD

**Issue by ptk1601** [aertslab/scenicplus#520]
Hello!

I am having issues with the find_diff_features function in the pycisTopic library as a part of the SCENIC+ workflow. I have not had any issues generating the previous, required dataframes in the workflow according to the live lecture aside from perhaps a few NaNs in the Seurat_cell_type column of my cistopic_obj. But for some reason when I run find_diff_features, Jupyter Notebook tells me that a local Ray instance has started but then cuts off right there without any additional processes, and I am left with an empty markers_dict. Is there something I can check to fix this? Here is the code I am running. Thank you so much for the help!

import ray

markers_dict= find_diff_features(
cistopic_obj,
imputed_acc_obj,
variable='Seurat_cell_type',
var_features=variable_regions,
contrasts=None,
adjpval_thr=0.05,
log2fc_thr=np.log2(1.5),
n_cpu=5,
_temp_dir='/tmp',
split_pattern = None
)

**Comment by SeppeDeWinter** [comment]
Hi @ptk1601 

Please don't open duplicate issues: https://github.com/aertslab/pycisTopic/issues/195.

Best,

Seppe
