### ISSUE TITLE
Test data in scenicplus and pycisTopic jupyter notebook seem lost. 

### ISSUE THREAD

**Issue by wangmeijiao** [aertslab/scenicplus#62]
Hi, 

 Here I report that test datasets (10x_multiome_brain_Seurat.loom and other input files) in both scenicplus (https://github.com/aertslab/scenicplus/blob/main/docs/Scenicplus_step_by_step-RTD.ipynb) and
 pycisTopic (https://pycistopic.readthedocs.io/en/latest/Single_sample_workflow-RTD.html) jupyter
 notebooks seem lost.  Perhaps I miss some information within that notebook? I understand one can carry out seurat analysis from the downloaded dataset, but it would be great if the author can support a ready-to-use one ^_^. Thanks a lot!

Best,
Meijiao

**Comment by SeppeDeWinter** [comment]
Hi @wangmeijiao 

You can get the files from https://scope.aertslab.org/#/scenic-v2, press the little 
<img width="26" alt="image" src="https://user-images.githubusercontent.com/5092871/201103162-d71a2876-8d8b-40e7-9c85-44c4d48a76fd.png"> "save" icon next to the file name.

They are the fully processed files, but they should contain everything to rerun the tutorial.

Best,

Seppe

**Comment by GRPHemato** [comment]
Okey~, nice tool  'SCENIC+' by the way!

**Comment by wangmeijiao** [comment]
Okey~, nice tool 'SCENIC+' by the way!
