### ISSUE TITLE
Tutorial 10x multiome - ATAC processing

### ISSUE THREAD

**Issue by JasonOSS** [aertslab/scenicplus#63]
**Describe the bug**
Hi, I am trying to run the tutorial for 10x multiome but I am getting an error when processing ATAC seq part.

**To Reproduce**
```
from pycisTopic.pseudobulk_peak_calling import export_pseudobulk
bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
                 variable = 'celltype',                                                                     # variable by which to generate pseubulk profiles, in this case we want pseudobulks per celltype
                 sample_id_col = 'sample_id',
                 chromsizes = chromsizes,
                 bed_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  # specify where pseudobulk_bed_files should be stored
                 bigwig_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bw_files/'),# specify where pseudobulk_bw_files should be stored
                 path_to_fragments = fragments_dict,                                                        # location of fragment fiels
                 n_cpu = 8,                                                                                 # specify the number of cores to use, we use ray for multi processing
                 normalize_bigwig = True,
                 remove_duplicates = True,
                 _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
                 split_pattern = '-')
```

**Error output**
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In [25], line 2
      1 from pycisTopic.pseudobulk_peak_calling import export_pseudobulk
----> 2 bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
      3                  variable = 'celltype',                                                                     # variable by which to generate pseubulk profiles, in this case we want pseudobulks per celltype
      4                  sample_id_col = 'sample_id',
      5                  chromsizes = chromsizes,
      6                  bed_path = os.path.join(work_dir, '~/scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  # specify where pseudobulk_bed_files should be stored
      7                  bigwig_path = os.path.join(work_dir, '~/scATAC/consensus_peak_calling/pseudobulk_bw_files/'),# specify where pseudobulk_bw_files should be stored
      8                  path_to_fragments = fragments_dict,                                                        # location of fragment fiels
      9                  n_cpu = 8,                                                                                 # specify the number of cores to use, we use ray for multi processing
     10                  normalize_bigwig = True,
     11                  remove_duplicates = True,
     12                  _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
     13                  split_pattern = '-')

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py:164, in export_pseudobulk(input_data, variable, chromsizes, bed_path, bigwig_path, path_to_fragments, sample_id_col, n_cpu, normalize_bigwig, remove_duplicates, split_pattern, use_polars, **kwargs)
    162 # Create pseudobulks
    163 if n_cpu > 1:
--> 164     ray.init(num_cpus=n_cpu, **kwargs)
    165     ray_handle = ray.wait(
    166         [
    167             export_pseudobulk_ray.remote(
   (...)
    181         num_returns=len(groups),
    182     )
    183     ray.shutdown()

File ~/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/.local/lib/python3.8/site-packages/ray/_private/worker.py:1420, in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, namespace, runtime_env, storage, **kwargs)
   1378     ray_params = ray._private.parameter.RayParams(
   1379         node_ip_address=node_ip_address,
   1380         raylet_ip_address=raylet_ip_address,
   (...)
   1414         node_name=_node_name,
   1415     )
   1416     # Start the Ray processes. We set shutdown_at_exit=False because we
   1417     # shutdown the node in the ray.shutdown call that happens in the atexit
   1418     # handler. We still spawn a reaper process in case the atexit handler
   1419     # isn't called.
-> 1420     _global_node = ray._private.node.Node(
   1421         head=True, shutdown_at_exit=False, spawn_reaper=True, ray_params=ray_params
   1422     )
   1423 else:
   1424     # In this case, we are connecting to an existing cluster.
   1425     if num_cpus is not None or num_gpus is not None:

File ~/.local/lib/python3.8/site-packages/ray/_private/node.py:198, in Node.__init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    195 else:
    196     self._webui_url = ray._private.services.get_webui_url_from_internal_kv()
--> 198 self._init_temp()
    200 # Validate and initialize the persistent storage API.
    201 if head:

File ~/.local/lib/python3.8/site-packages/ray/_private/node.py:398, in Node._init_temp(self)
    390     temp_dir = ray._private.utils.internal_kv_get_with_retry(
    391         self.get_gcs_client(),
    392         "temp_dir",
    393         ray_constants.KV_NAMESPACE_SESSION,
    394         num_retries=NUM_REDIS_GET_RETRIES,
    395     )
    396     self._temp_dir = ray._private.utils.decode(temp_dir)
--> 398 try_to_create_directory(self._temp_dir)
    400 if self.head:
    401     self._session_dir = os.path.join(self._temp_dir, self.session_name)

File ~/.local/lib/python3.8/site-packages/ray/_private/utils.py:916, in try_to_create_directory(directory_path)
    910 """Attempt to create a directory that is globally readable/writable.
    911 
    912 Args:
    913     directory_path: The path of the directory to create.
    914 """
    915 directory_path = os.path.expanduser(directory_path)
--> 916 os.makedirs(directory_path, exist_ok=True)
    917 # Change the log directory permissions so others can use it. This is
    918 # important when multiple people are using the same machine.
    919 try_make_directory_shared(directory_path)

File ~/.conda/envs/scenicplus/lib/python3.8/os.py:213, in makedirs(name, mode, exist_ok)
    211 if head and tail and not path.exists(head):
    212     try:
--> 213         makedirs(head, exist_ok=exist_ok)
    214     except FileExistsError:
    215         # Defeats race condition when another thread created the path
    216         pass

File ~/.conda/envs/scenicplus/lib/python3.8/os.py:213, in makedirs(name, mode, exist_ok)
    211 if head and tail and not path.exists(head):
    212     try:
--> 213         makedirs(head, exist_ok=exist_ok)
    214     except FileExistsError:
    215         # Defeats race condition when another thread created the path
    216         pass

File ~/.conda/envs/scenicplus/lib/python3.8/os.py:213, in makedirs(name, mode, exist_ok)
    211 if head and tail and not path.exists(head):
    212     try:
--> 213         makedirs(head, exist_ok=exist_ok)
    214     except FileExistsError:
    215         # Defeats race condition when another thread created the path
    216         pass

File ~/.conda/envs/scenicplus/lib/python3.8/os.py:223, in makedirs(name, mode, exist_ok)
    221         return
    222 try:
--> 223     mkdir(name, mode)
    224 except OSError:
    225     # Cannot rely on checking for EEXIST, since the operating system
    226     # could give priority to other errors like EACCES or EROFS
    227     if not exist_ok or not path.isdir(name):

PermissionError: [Errno 13] Permission denied: '/scratch/leuven'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python: 3.8
 - SCENIC+: '0.1.dev452+g22735ca'
 - 

**Additional context**

**Comment by SidG13** [comment]
Not the original developer here, but the error is because the temp file '/scratch/leuven' isn't on your machine. You need to set that before running (i.e., change the variable ```tmp_dir``` to some path)

**Comment by JasonOSS** [comment]
Hi @SidG13,

I tried to change the directory in `tmp_dir` but then I am getting some other error:

``` 
Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup. 
```

it looks like the directory '/scratch/leuven' should have been created earlier but I dont see it anywhere in the script

**Comment by SidG13** [comment]
Assuming you're running a jupyter notebook, maybe try restarting the kernel? In the [example notebook](https://github.com/aertslab/scenicplus/blob/main/notebooks/pbmc_multiome_tutorial.ipynb), you just set ```tmp_dir``` to some path on your machine with enough memory. You'll find that code block in the "scATAC-seq preprocessing using pycisTopic" section.

**Comment by SeppeDeWinter** [comment]
Hi @JasonOSS 

There seems to be an issue initialising ray.

How many cores do you have available on your machine?

Can you try running the following code, and report the output? 

```python

import ray
ray.init(num_cpus=4)
ray.shutdown()

```

p.s.
@SidG13, thank you for the help!

Best,

Seppe

**Comment by Mengzhiyaa** [comment]
Hi @SeppeDeWinter 
I have the same issue with @SidG13.
I have run the following code:
```
import ray
ray.init(num_cpus=4)
ray.shutdown()
```
The output is
`2022-11-11 12:30:40,676	INFO worker.py:1519 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8268 
`
And then I try to run the **export_pseudobulk** function with different cores, and I can run this function successfully when I set **n_cpu = 1**.

**Comment by Mengzhiyaa** [comment]
Hi @SeppeDeWinter,  I figured out the cause of this problem, which is the **_temp_dir** parameters passed to ray.init(). All function I mentioned above could be run  successfully.

**Comment by SeppeDeWinter** [comment]
@Mengzhiyaa 

That's what I was thinking as well. 
I'm glad you were able to fix the problem.


Best,

Seppe
