### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by klgoss** [aertslab/scenicplus#83]
Hello, thanks for creating this wonderful tool!

I installed SCENIC+ in a conda environment on HPC. When trying `from scenicplus.scenicplus_class import SCENICPLUS, create_SCENICPLUS_object` , I keep getting an import error: `ImportError: /storage/home/hcoda1/1/kgoss8/.conda/envs/scenicplus/lib/python3.8/site-packages/ncls/src/ncls.cpython-38-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr` . My python version is 3.8.15 and SCENIC+ version is 0.1.dev456+g9662363. Has anyone else encountered this issue?

**Comment by SeppeDeWinter** [comment]
Hi

This does not look like a SCENIC+ specific problem. It looks like something went wrong while compiling cython.

This stack-overflow question might help: https://stackoverflow.com/questions/49524083/importing-any-module-in-cython-file-gives-undefined-symbol-error

Best,

Seppe
