### ISSUE TITLE
Attribute Error: create_SCENICPLUS_object, adata.raw.to_adata

### ISSUE THREAD

**Issue by SidG13** [aertslab/scenicplus#90]
**Describe the bug**

I'm running the code block below

```python
from scenicplus.scenicplus_class import create_SCENICPLUS_object
import numpy as np
scplus_obj = create_SCENICPLUS_object(
    GEX_anndata = adata.raw.to_adata(),
    cisTopic_obj = cistopic_obj,
    menr = menr,
    bc_transform_func = lambda x: f'{x}-10x_pbmc' #function to convert scATAC-seq barcodes to scRNA-seq ones
)
scplus_obj.X_EXP = np.array(scplus_obj.X_EXP.todense())
scplus_obj
```
but running into a problem reading my adata file. 

My anndata seems fine and structured properly:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/36648847/212996077-9431f9cc-a746-4263-b352-6dbc1003edc3.png">

**Error output**
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/36648847/212996191-28233601-e231-4d08-8c05-78051ef3f340.png">

I'm also wondering how I should reformat the "bc_transform_func" line, how do I view the barcode information in both objects to know what to change?

**Version (please complete the following information):**
 - Python: Python 3.8
 - SCENIC+: 0.1.dev453+gf322c5b

Thanks!

**Comment by SeppeDeWinter** [comment]
Hi @SidG13 

You probably did not save your raw gene expression counts in `adata.raw`, hence the `NoneType` error. 

See the data normalisation step in the tutorial (https://scenicplus.readthedocs.io/en/latest/pbmc_multiome_tutorial.html#Data-normalization)

```python
adata.raw = adata #<---
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
adata = adata[:, adata.var.highly_variable]
sc.pp.scale(adata, max_value=10)
```

As for your second question.

For the scRNA-seq you can see the barcodes like this: 

```python

adata.obs_names

```

for the scATAC-seq you can see the barcodes like this:

```python

cistopic_obj.cell_names

```

I hope this helps.

Best,

Seppe

**Comment by SidG13** [comment]
Thanks! That was very helpful! Sorry, I'm quite new to anndata objects so I'm running into another issue now where the scplus_obj.X isn't being initialized. For reference, here is my object: 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/36648847/214113241-fa7b865c-9549-4eca-b05c-e3402c959763.png">
But when running the next line, I get an issue:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/36648847/214113406-c224c5dc-8be8-4b93-9527-067acf3bc767.png">

Running my regular adata.X produces an expected array. Any ideas on how to troubleshoot this?

**Comment by SeppeDeWinter** [comment]
Hi @SidG13 

The `scplus_obj` indeed does not have the attribute `X`, the gene expression matrix is store in `X_EXP` instead. So everything is in fact working correclty!

Best,

Seppe
